### ISSUE TITLE
[Bug]: JEI not showing Resourceful Bees items and process

### ISSUE THREAD

**Issue by TonTonAsoX** [AllTheMods/ATM-6#3173] opened 2023-04-10 16:09 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

JEI don't show any recipes or uses for all the Resourceful Bees items (Centrifuge, or Honeycomb for example). Clients & server are on the same version.

### latest.log

https://gist.github.com/TonTonAsoX/468313591bdf2037b473a99af464f558

**Comment by jeremiahwinsley** [comment] 2023-04-10 18:35
Caused by / duplicate of #3174

**Closed by jeremiahwinsley** 2023-04-10 18:35 UTC
Labels: Bug

**Comment by TonTonAsoX** [comment] 2023-04-10 19:48
I change the resourcefulbees folder on the server to the config from client side, and I can't see uses for Centrifuge or Honeycombs
