### ISSUE TITLE
Ender Dragon not spawning

### ISSUE THREAD

**Issue by Devoidsoul675** [AllTheMods/ATM-6#357] opened 2020-11-22 15:36 UTC
During my first playthrough on 1.3.0, when I first arrived at the end the dragon did not spawn. No portal back no nothing, looked online for a solution couldnt find anything.  Deleted the Dim 1 folder, tried again, same story.  Deleted the entire world, started completely fresh, total server wipe. Ive made it to the end again and again no dragon.

What do i do?

**Comment by InsideBSI** [comment] 2020-11-22 16:11
duplicate of #333

**Closed** 2020-11-24 14:19 UTC
Labels: Question
