### ISSUE TITLE
Request Yellorium seed Recipe to be added to Mystical Agriculture

### ISSUE THREAD

**Issue by jblankenship30** [AllTheMods/ATM-6#459] opened 2020-12-01 02:32 UTC
**Is your feature request related to a problem? Please describe.**
Currently, you can use the Mystical Agriculture infusion alter with yellorium to craft uranium seeds but there is no essence crafting recipe available to create uranium or yellorium ingots.

**Describe the solution you'd like**
Create an alternate essence crafting recipe to create yellorium ingots or add recipe to Mystical Agriculture for yellorium seeds/essence along with its corresponding essence crafting recipe.

**Comment by RogueLogix** [comment] 2020-12-01 05:27
What do you need specifically Yellorium ingots for? Also, this is basically a duplicate of your own issue #458.

**Comment by jblankenship30** [comment] 2020-12-01 06:14
I'm am trying to automate fuel production for Bigger Reacters

**Comment by RogueLogix** [comment] 2020-12-01 06:17
then any uranium will do you just fine, so, #458.

**Closed** 2020-12-02 03:11 UTC
Labels: Enhancement
