### ISSUE TITLE
Teleport from Allthemodium

### ISSUE THREAD

**Issue by RickyGeo** [AllTheMods/ATM-6#961] opened 2021-01-29 19:58 UTC
The teleport dost work and i cant use Waystone to mining dimension or the Other Dimension 
i use ATM 1.16.5 
for Screenshot i thing it dosnt need that cause just teleport

**Comment by MerimaDev** [comment] 2021-01-29 20:32
> The teleport dost work and i cant use Waystone to mining dimension or the Other Dimension
> i use ATM 1.16.5
> for Screenshot i thing it dosnt need that cause just teleport

For me restarting the server worked out, after 1 restart everything worked fine.

**Comment by whatthedrunk** [comment] 2021-01-29 21:46
Duplicate of https://github.com/AllTheMods/ATM-6/issues/957

**Closed by whatthedrunk** 2021-01-29 21:46 UTC
Labels: Bug
