### ISSUE TITLE
[Crash]: 1.8.12 - Crash on Ritual of the Martyr Activation

### ISSUE THREAD

**Issue by Tman7077** [AllTheMods/ATM-6#2787] opened 2021-12-10 07:31 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.12

### What happened?

Upon activating the Ritual of the Martyr (the Woot integration for Blood Magic), it crashes every time. I have tried it without any other blocks in the area of the ritual stones, too, so that isn't the problem. Additionally, it crashes if I attempt to re-load into the world after the "initial" crash, so I have to load a backup to get into the world again.
Here are crash reports for all of the times I tried:
With performance mods installed (Calcium, Magnesium, Observable, RoadRunner, Sulfuric):
Crash [1](https://github.com/AllTheMods/ATM-6/files/7690500/crash-2021-12-09_22.29.48-server.txt) ([2](https://github.com/AllTheMods/ATM-6/files/7690504/crash-2021-12-09_22.36.11-server.txt) [3](https://github.com/AllTheMods/ATM-6/files/7690510/crash-2021-12-09_22.46.03-server.txt) [4](https://github.com/AllTheMods/ATM-6/files/7690515/crash-2021-12-09_23.00.50-server.txt) [5](https://github.com/AllTheMods/ATM-6/files/7690517/crash-2021-12-09_23.08.38-server.txt) if you care... I didn't need to crash it 5 times but I wanted to make sure, I also moved the ritual stones to only have air blocks in between each other at one point in this chain of crashes.)
With no additional mods, just the base pack:
Crash [6](https://github.com/AllTheMods/ATM-6/files/7690528/crash-2021-12-09_23.31.51-server.txt) ([7](https://github.com/AllTheMods/ATM-6/files/7690590/crash-2021-12-09_23.41.43-server.txt))
Crash [8](https://github.com/AllTheMods/ATM-6/files/7690700/crash-2021-12-09_23.59.57-server.txt): Before attempting to activate the ritual, I broke the Woot Factory Heart in case that was the problem, as I have had crashes when Woot tries to assemble its multiblock before.
Crash [9](https://github.com/AllTheMods/ATM-6/files/7690802/crash-2021-12-10_00.18.26-server.txt): Here, I tested it in a brand-spankin' creative flat world. The ritual seemed like it was going to form, as it didn't crash _immediately_, but it gave me never-ending nausea, which I assumed meant it didn't like that I didn't have LP in my soul network. I pulled out a blood orb and as soon as I used it (therefore putting LP in my network), it crashed. So probably something about the yeetus deletus of the LP in the network is the cause of the crash. At this point, I gave up trying things and adding "just one more" thing to this bug report.. here you go. :) Crash 9 is the crash report that I pasted to [gist.github.com](https://gist.github.com) per request below.

### Crash Log

https://gist.github.com/Tman7077/fbd9be05d1c598bbc8d99c314189bba3

**Comment by jeremiahwinsley** [comment] 2021-12-10 19:00
Duplicate of https://github.com/AllTheMods/ATM-6/issues/2554

**Closed by jeremiahwinsley** 2021-12-10 19:00 UTC
Labels: Crash
