### ISSUE TITLE
plz help me fix missing textures 

### ISSUE THREAD

**Issue by cM1cr0** [AllTheMods/ATM-6#148] opened 2020-10-05 19:55 UTC
soo basicly all of the textures are missing form applied energistics 2 dose anyone know how to fix this?
![dawdsawd](https://user-images.githubusercontent.com/72414131/95125525-bc9ecd00-071a-11eb-8560-6c056fbc1079.JPG)
![asdawd](https://user-images.githubusercontent.com/72414131/95125527-bd376380-071a-11eb-8370-9a7e78b74cf4.JPG)
![awdsawd](https://user-images.githubusercontent.com/72414131/95125529-bd376380-071a-11eb-8ae6-bb9e444d0d23.JPG)
![asdawrf](https://user-images.githubusercontent.com/72414131/95125530-bd376380-071a-11eb-99bf-fae4798cda20.JPG)
![2020-10-05_14 46 06](https://user-images.githubusercontent.com/72414131/95125532-bd376380-071a-11eb-9d69-dfead668ed06.png)

**Comment by cM1cr0** [comment] 2020-10-05 19:57
im on windows 10 
![image](https://user-images.githubusercontent.com/72414131/95125727-05568600-071b-11eb-82cb-1fdf92d27989.png)

**Comment by WhitePhant0m** [comment] 2020-10-05 20:01
Duplicate of #89

**Comment by WhitePhant0m** [comment] 2020-10-05 20:01
You can see how to fix it in that issue

**Closed by WhitePhant0m** 2020-10-05 20:01 UTC

**Comment by cM1cr0** [comment] 2020-10-05 20:15
it fixed applied energistics 2 but not silent gear 
![image](https://user-images.githubusercontent.com/72414131/95127407-8ca4f900-071d-11eb-980c-a8a591c04302.png)

**Comment by WhitePhant0m** [comment] 2020-10-05 20:26
That must be a issue with silent gear itself then, not much I can do about that. does it happen without optifine?
