### ISSUE TITLE
Crafting Recipes broken 

### ISSUE THREAD

**Issue by daniel124356** [AllTheMods/ATM-6#18] opened 2020-07-24 06:24 UTC
Rats cheese blocks dont turn into cheese, basic capacitor cant be turned into large, if you put a basic capacitor into crafting bench etc a "small old fancy button" comes out as the recipe and disappears after half a second, unable to make flour and potato flour, Only started happening after updating to 0.19 of atm6, tried reinstalling to whole sever but the issue still persists

**Comment by Niklars** [comment] 2020-07-24 07:29
I can verify the same issue. Works in singleplayer for me but not on server.

**Comment by R-Jimenez** [comment] 2020-07-24 12:41
Also seeing issues with recipes, in my case a few of the Refined Storage ones (raw processors). Notably like above the issue is only on our multiplayer server, and all recipes work fine in my singleplayer test world.

**Comment by WhitePhant0m** [comment] 2020-07-24 16:23
You can try /reload to fix these problems for now, there has been some recipe problems on the test servers as well and the reload command fixed those.

**Comment by R-Jimenez** [comment] 2020-07-24 18:02
The above fixed it for me. Good to know, and don't mind the restarting for now. Cheers!

**Comment by whatthedrunk** [comment] 2020-07-25 18:24
Alright this should be fixed in 0.20. Just tested cheese and processors and they work on a server without reload. I will push it in a few mins after a little more testing.

**Closed by whatthedrunk** 2020-07-25 18:24 UTC
