### ISSUE TITLE
[1.6.10]I can't join my ATM6 world. 

### ISSUE THREAD

**Issue by leelcheese** [AllTheMods/ATM-6#1875] opened 2021-06-21 18:33 UTC
**ATM6 latest 1.6.10**
**I can't join my ATM6 world**
I can't join my world i think it's corrupted.

**Screenshots**
If you need i can send some on what social platform you want. I just created this account to ask this so idk how this site works. sorry.

**Additional context**
I was on The End searching for some unobtanium found a spawner of endermite, i think, and the game crashed or i left, i forgot what i did sorry, and i can't join it now.
I use curseforge as launcher btw.

**Logs**
https://gist.github.com/leelcheese/9228dba94418f4ad035359bafeebcd33

**Comment by hyflicker** [comment] 2021-06-21 19:56
@leelcheese First off is this a server or single player world? The logs you provided look like server logs and are incomplete. The server never prepares spawn. If the client and/or server crashed when the issue happened please provide crash logs. Also, if this is a server try loading off of a backup world.

**Comment by leelcheese** [comment] 2021-06-21 20:03
@hyflicker hello, it's actually a singleplayer world, about the logs i just copied whats inside. I will try tomorrow because I will go to sleep now. If you find anything else please consider telling me. Thank you!

**Comment by hyflicker** [comment] 2021-06-21 20:16
@leelcheese At the bottom of the provided logs it says it generated a Crash report. You can access this by going to the curse forge launcher going to the ATM6 pack click on the pack instead of play. Click the three vertical dots and click open folder. Once open navigate to crash-reports and provide the most recent file. All crash reports are named with data and time code. Ex: crash-2021-06-16_13.56.08-client.txt

**Comment by leelcheese** [comment] 2021-06-21 20:19
@hyflicker thank you so much, i will reply tomorrow with the recent logs. Good night :)

**Comment by leelcheese** [comment] 2021-06-22 10:44
@hyflicker 
[crash-2021-06-21_21.14.47-server.txt](https://github.com/AllTheMods/ATM-6/files/6693548/crash-2021-06-21_21.14.47-server.txt)
 here s the crash report

**Comment by hyflicker** [comment] 2021-06-23 02:03
Looks like your issue is being caused by endermites. You can follow this forum to get your singleplayer world to peaceful and that should despawn all the mobs. [https://www.reddit.com/r/Minecraft/comments/986jo2/is_is_possible_to_change_a_single_player_worlds/](url)
Please close this thread if it fixes your issue and the crashes stop.

**Closed** 2021-06-23 11:07 UTC
Labels: Bug
