### ISSUE TITLE
Backpack in Tinker's crafting station breaks the world.

### ISSUE THREAD

**Issue by JackRHainsworth** [AllTheMods/ATM-6#2093] opened 2021-07-31 15:35 UTC
Placing a backpack from the sophisticated backpacks mod in a tinker's crafting station crashes the world, and makes it impossible to re-open the world without loading a backup.

**Comment by FragsAreUs** [comment] 2021-08-01 02:19
I cant +1 on this works fine in the original minecraft workbench but when using it with the tinkers it crashes giving a entity render issue

**Comment by blinkinglight** [comment] 2021-08-01 12:57
https://pastebin.com/RLCy4jmX same problem, wanted to craft iron tier backpack in tinkers crafting station

**Comment by BovineShaman** [comment] 2021-08-02 17:32
@blinkinglight @JackRHainsworth try updating sophisticated backpacks and let us know if that fixes the problem.

**Comment by blinkinglight** [comment] 2021-08-02 17:51
yes, update mod fixes issue

**Comment by blinkinglight** [comment] 2021-08-02 17:52
also that happens than you try to upgrade basic backpack to iron tier in tinkers table.  ( maybe because it renders items on the tables and problem was with backpack mod itsefl)

**Comment by ladylexxie** [comment] 2021-08-30 05:16
Duplicate of #2079

**Closed by ladylexxie** 2021-08-30 05:16 UTC
Labels: Bug, Crash, Waiting response
