### ISSUE TITLE
Centrifuge dont work serverside

### ISSUE THREAD

**Issue by Shadowmaster09** [AllTheMods/ATM-6#1428] opened 2021-04-15 04:51 UTC
I've disvocered that the recipes for the Centrifuges are missing on version 1.10b serverside. If i start the same world on Singleplayer the recipes are working and so the Centrifuge. Also tried to reinstall server couple of times and also tried Java 8, 11. Hope you can fix it soon or give tipps for workaround

**Comment by RogueLogix** [comment] 2021-04-15 04:53
duplicate of https://github.com/AllTheMods/ATM-6/issues/1384

**Closed** 2021-04-15 04:57 UTC
