### ISSUE TITLE
Dragon forge's recipes not showing in JEI

### ISSUE THREAD

**Issue by isabellebarroca** [AllTheMods/ATM-6#3017] opened 2022-03-29 00:58 UTC
The ice and fire dragon forge recipes (like dragonsteel. alloys of allthemodium) are not showing in JEI, im playing in a server and in my friend's JEI is showing. I'm playing in the 1.8.22 version of the modpack.

**Comment by radiomike** [comment] 2022-04-01 21:59
Duplicate of #2340

**Closed** 2022-04-12 01:46 UTC
