### ISSUE TITLE
RAM minimalization options / memory leaks

### ISSUE THREAD

**Issue by Krayfighter** [AllTheMods/ATM-6#2721] opened 2021-11-23 14:52 UTC
### What would you like to know?

I have what seems to be way too much ram allocated to ATM 6, (10 gigs) which eventually get used in-game.

I have my render distance at 10 chunks. when I join my local world it starts at a low allocation (about <60%), but the longer I play the game, and the more I explore the world, the more ends up allocated, but it increases slowly, which makes me think it is a memory leak.

restarting the world fixes the problem, but temporarily, and having local players join my world increases the rate of memory increase (on top of the initial increase if they are rendering new chunks)

do the devs know what this phenomenon is and/or are there memory minimalization options, I don't need it because I have the ram, but others may not.

**Comment by Krayfighter** [comment] 2021-11-23 14:53
forgot to say this, but it might be important that I am using Linux, but maybe not

**Comment by ClintRajaniemi** [comment] 2021-11-26 17:28
What's not clear to me is whether you have allocated 10GB RAM to the game or if you're saying it's going over the allocation you've set.

What have you set for the server's max RAM? If you've allocated 10GB, then I'm not sure what the issue is with it using that.

Slowly increasing RAM doesn't seem to indicate a memory leak. It *could* be, but I don't believe that's a good indicator. I'd expect a slow increase after the initial game load since loading the game/mods should be the largest allocation. Everything else is incremental. I also don't find it odd that more players joining increases the rate at which RAM is consumed.

I'm not well versed in Java so take this explanation as naive (at best). Say that you've manually allocated 10GB RAM for the server. It's my understanding that this doesn't account for what the JVM might use (there could be other things as well) only the game itself and mods. In other words, if 10GB usage is tight for your server, it's probably too high since there will be other RAM usage from the JVM.

If I've misunderstood something, it would help if you could clarify things based on my description above.

**Comment by bobothehobo2** [comment] 2021-11-28 22:11
I'm a long time Java Architect so maybe I can help a little :).  Without having the exact details of your setup it would be a guessing game as to what your issue is if you have one.  I personally would need this info to help

1. Are you in single player?  If not, are you talking about the server or the client or both?
2. Java args you are using for each machine if on a server (if applicable)
3. What versions of Java are you running (8, 9, 10 etc)
4. What JVM provider are you using (OpenJDK, Oracle etc)
5. Are you on a dedicated server, shared resources server or home box
6. If you are at home do you run both server and client on one box?
7. Is it going past the allocated ram?  If so by how much?
8. Are you running optifine/forge?  Resource packs? How detailed are the resource packs? Shaders? Which one?
9. What's the total ram on the box in question

  Generally speaking, unless you set the -Xms(starting allocation) to match the -Xmx(max allocation to shoot for) it will always grow from startup.  The "beginning" ram allocation is just enough to get the game loaded.  The JVM will continue to grow over time as objects load and will decrease when they are collected by gc it it's a very dynamic env so don't be surprised that it isn't sticking to 10g.  Your gc strategy has a lot to do with how large the heap will get before it's starts to collect the tighter correlated object references.   The jvm will expand it's pool to whatever is needed to run the app until it runs out of memory to take.  So if there is a lot going on in your world (machines, chunkloading etc) it will add to it's needs.  Everything you are experiencing is in the normal process of running a jvm provided you don't have things set extremely tight through your args (which 99% of minecrafters don't).  So a good blanket rule for MC is expect it to run 2-4 gigs higher than what you set it to.  Now, there are conditions that come into play like how old is the world, how many people are playing, how far through the pack you are, how many chunks have you generated/loaded etc etc. 

  Giving you an example of my server, when I loaded it fresh with a new world it only took 4 gigs to run.  For a month it was stable at that mark with 2 people consistently on the server.  Currently, there are 4 people on and two of us have basically endless resources coming in from void miners.  Since you need to have one set up in the 3 main dimensions to grab everything that means 3 dimensions are loaded 24/7.  We also have the mining dimension loaded 24/7.  There's also a lot of endgame automation going on that's chunkloaded.  Mob grinders as well.  So there is a fair amount of things needing memory.  My server is currently running at 6.3 gigs and climbing.

  Now I personally play with 512x resource packs (Both MC and Mods from bdcraft which eat memory up quickly) because my pc is a beefcake.  I allocate 32g (half of my memory) to MC.  Right now I'm pushing 25g on my client.  And that's with optimization and offloading to my gpu as much as possible.  My wife has just a base MC 256x resource pack and nothing else and her laptop runs below the 16g allocated by a few gigs.

  Lastly, in order to tell if there is a memory leak (which I promise you MC is one big memory leak and there's nothing that can be done unless you want to re-code the entire game and most of the mods) it's really tricky.  Memory leaks will 100% always end up in an OutOfMemoryException (OOM) and they are the absolute hardest thing to find and fix in anyone's career as a Java dev.  I've been doing this for 20 yrs and I still cringe at that exception because what took someone 2 mins to write will take an entire teams troubleshooting for up to months on end to identify the issue. Most common one is not closing a DB connection after opening it so when the object is being gathered for gc there is a strong reference to that object so the JVM let's it sit there (as it should).  So that's partially (the other part being all the other conditions) why restarting helps because everything is trashed in that process.  But honestly, IMHO I'm fine with the leaks because there are thousands of people in the modding community that may well not be professional devs, but they make MC MC and are awesome all the same.  Hopefully this helps you some. :)

**Closed** 2021-12-06 22:34 UTC
Labels: Question
