### ISSUE TITLE
Official Mod Suggestions for ATM6

### ISSUE THREAD

**Issue by whatthedrunk** [AllTheMods/ATM-6#1] opened 2020-06-04 20:29 UTC
We are now entering ATM6. Leave suggestions below with links to curseforge.
If I deleted your message it was either added or rejected. I will make a proper list soon!

FYI we cannot add BOP yet but if you want to create a new world go ahead and add it manually. Old worlds with Rats cannot add BOP at the moment.

**Comment by bmastergamer** [comment] 2020-06-28 01:21
https://www.curseforge.com/minecraft/mc-mods/look-at-that
https://www.curseforge.com/minecraft/mc-mods/darker-loading-screen
https://www.curseforge.com/minecraft/mc-mods/auto-feeder-helmet

**Comment by Commoble** [comment] 2020-06-28 03:19
[Tubes Reloaded](https://www.curseforge.com/minecraft/mc-mods/tubes-reloaded)

**Comment by TheRoboticEng** [comment] 2020-06-28 11:55
https://www.curseforge.com/minecraft/mc-mods/tinkers-mechworks

**Comment by bmastergamer** [comment] 2020-06-30 01:51
https://www.curseforge.com/minecraft/mc-mods/ring-of-the-miner-forge
https://www.curseforge.com/minecraft/mc-mods/ring-of-attraction-forge
https://www.curseforge.com/minecraft/mc-mods/ring-of-repair-forge
https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers-forge
https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators-forge
https://www.curseforge.com/minecraft/mc-mods/inventory-spam
https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption
sorry there's a lot

**Comment by Commoble** [comment] 2020-06-30 15:11
[Potion of Bees](https://www.curseforge.com/minecraft/mc-mods/potion-of-bees/files/2993038)

**Comment by Commoble** [comment] 2020-06-30 21:08
[Bag of Yurting](https://www.curseforge.com/minecraft/mc-mods/bag-of-yurting)

**Comment by naqaden** [comment] 2020-07-06 07:56
[Name Pain](https://www.curseforge.com/minecraft/mc-mods/name-pain/)

**Comment by BaronNoogie** [comment] 2020-07-07 23:21
Rats! https://www.curseforge.com/minecraft/mc-mods/rats

**Comment by ExonHUN** [comment] 2020-07-09 15:58
https://www.curseforge.com/minecraft/mc-mods/columns
https://www.curseforge.com/minecraft/mc-mods/essentials
https://www.curseforge.com/minecraft/mc-mods/dye-extension
https://www.curseforge.com/minecraft/mc-mods/simple-planes
https://www.curseforge.com/minecraft/mc-mods/premium-wood
https://www.curseforge.com/minecraft/mc-mods/actually-useful-stonecutter
https://www.curseforge.com/minecraft/mc-mods/improved-stations-forge
https://www.curseforge.com/minecraft/mc-mods/better-stones
https://www.curseforge.com/minecraft/mc-mods/blue-power

**Comment by bmastergamer** [comment] 2020-07-10 01:48
https://www.curseforge.com/minecraft/mc-mods/skyblock-items-reborn

**Comment by AleksiMK** [comment] 2020-07-10 03:00
[Iron Furnaces](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces)
Like Iron Barrels/Chests but for furnaces!

**Comment by AleksiMK** [comment] 2020-07-10 03:55
[Better than Mending](https://www.curseforge.com/minecraft/mc-mods/better-than-mending)
Makes mending repair items held also by taking xp from the player when sneaking

**Comment by paulspchelp-au** [comment] 2020-07-10 09:57
https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay
https://www.curseforge.com/minecraft/mc-mods/netherportalfix
https://www.curseforge.com/minecraft/mc-mods/light-overlay
https://www.curseforge.com/minecraft/mc-mods/structurize

**Comment by AleksiMK** [comment] 2020-07-10 10:13
[Botany Pots](https://www.curseforge.com/minecraft/mc-mods/botany-pots)
Like Bonsais but without the JEI issue

**Comment by AleksiMK** [comment] 2020-07-10 10:20
[Dank Storage](https://www.curseforge.com/minecraft/mc-mods/dank-storage)
Dank Null for 1.16

**Comment by AleksiMK** [comment] 2020-07-11 14:40
[DimStorage](https://www.curseforge.com/minecraft/mc-mods/dimstorage)
[Modular Routers](https://www.curseforge.com/minecraft/mc-mods/modular-routers)
We got these in ATM5 and they got updated to 1.16

**Comment by Stray216** [comment] 2020-07-12 01:53
[Xaero's World Map](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
There's already the Minimap and I really need to know where I have and haven't been.

**Comment by paulspchelp-au** [comment] 2020-07-12 08:33
https://www.curseforge.com/minecraft/mc-mods/vanilla-tools

**Comment by paulspchelp-au** [comment] 2020-07-12 08:34
https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty

**Comment by paulspchelp-au** [comment] 2020-07-12 08:43
https://www.curseforge.com/minecraft/mc-mods/nophantomnocry

**Comment by AleksiMK** [comment] 2020-07-12 18:38
[Torcherino](https://www.curseforge.com/minecraft/mc-mods/torcherino)
Torches to speed things up, just make recipes include some end game stuff or smth(like maybe antimatter from mekanism)

**Comment by paulspchelp-au** [comment] 2020-07-13 03:33
https://www.curseforge.com/minecraft/mc-mods/building-wands

**Comment by paulspchelp-au** [comment] 2020-07-13 09:40
https://www.curseforge.com/minecraft/mc-mods/fps-reducer

**Comment by paulspchelp-au** [comment] 2020-07-13 09:40
https://www.curseforge.com/minecraft/mc-mods/reauth

**Comment by triffman33** [comment] 2020-07-13 12:18
https://www.curseforge.com/minecraft/mc-mods/kleeslabs
https://www.curseforge.com/minecraft/mc-mods/passthrough-signs
https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs
https://www.curseforge.com/minecraft/mc-mods/server-tab-info
https://www.curseforge.com/minecraft/mc-mods/largefluidtank
https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores
https://www.curseforge.com/minecraft/mc-mods/simple-void-world

**Comment by MelanX** [comment] 2020-07-14 17:00
[Illuminations](https://www.curseforge.com/minecraft/mc-mods/illuminations)

**Comment by Stray216** [comment] 2020-07-15 14:31
[Rings of Ascension](https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension)
[Simple Void World](https://www.curseforge.com/minecraft/mc-mods/simple-void-world)

[dotHack Weapons](https://www.curseforge.com/minecraft/mc-mods/dothack-hack-weapons)

**Comment by AleksiMK** [comment] 2020-07-16 02:45
[Simple Magnets](https://www.curseforge.com/minecraft/mc-mods/simple-magnets)
Some early game magnets

**Comment by BaronNoogie** [comment] 2020-07-16 03:08
Arm the villages! 
https://www.curseforge.com/minecraft/mc-mods/guard-villagers

**Comment by bessiq** [comment] 2020-07-16 14:17
Probably unnecessary to suggest, but it just got ported:
https://www.curseforge.com/minecraft/mc-mods/morpheus

Also, it appears Forge finally fixed the issue with non-vanilla commands not working after a reload:
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.1-32.0.67/forge-1.16.1-32.0.67-changelog.txt

[Ma Essentials](https://www.curseforge.com/minecraft/mc-mods/maessentials) has updated to Forge version .67, and I can confirm their commands now work after reloading. HOWEVER, some other mods (that have their own commands) cause the game to crash on .67 - most notably The One Probe. So, I'd personally rather stay on .66 and have TOP until it gets updated. But I've always been on the fence about using Ma Essentials for survival anyway - but definitely handy for creative and server admin stuff. :)

**Comment by AleksiMK** [comment] 2020-07-16 19:08
[End Reborn](https://www.curseforge.com/minecraft/mc-mods/end-reborn)
Adds dungeons and stuff to the end, also, looks neat.

**Comment by AleksiMK** [comment] 2020-07-16 19:21
[Better Muffling](https://www.curseforge.com/minecraft/mc-mods/better-muffling)
Adds a block that makes nearby sounds quieter.

**Comment by karlreinert** [comment] 2020-07-16 22:33
https://www.curseforge.com/minecraft/mc-mods/morpheus
https://www.curseforge.com/minecraft/mc-mods/maessentials
https://www.curseforge.com/minecraft/mc-mods/modmenu

**Comment by AleksiMK** [comment] 2020-07-17 23:24
[Jasons Disenchantment](https://www.curseforge.com/minecraft/mc-mods/jasons-disenchantment-forge)
Allows moving enchantments from items to books. I'd like to have this as a replacement for corails enchant removal books

**Comment by AleksiMK** [comment] 2020-07-18 00:06
[Curious Elytra](https://www.curseforge.com/minecraft/mc-mods/curious-elytra)
Don't we have this in ATM5? Would be nice on this one too.

**Comment by Stray216** [comment] 2020-07-18 13:33
[Dark Paintings](https://www.curseforge.com/minecraft/mc-mods/dark-paintings)
it adds more painting variations

**Comment by paulspchelp-au** [comment] 2020-07-19 06:08
https://www.curseforge.com/minecraft/mc-mods/vanilla-tools
I add this in to my ver of all ATM6 works well

**Comment by bessiq** [comment] 2020-07-19 14:50
https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine
I kinda prefer it to OE, and who knows if/when OE will get ported. Even if the exhaustion was set really high to encourage other options, would still be welcome imo.

**Comment by bessiq** [comment] 2020-07-19 23:10
Probably another unnecessary suggestion, but a _very quiet_ tool crafting mod has been ported:
https://www.curseforge.com/minecraft/mc-mods/silent-gear

**Comment by bessiq** [comment] 2020-07-20 15:14
https://www.curseforge.com/minecraft/mc-mods/polymorph

Bad news: it doesn't let you change into animals or monsters.
Good news: it is a nice workaround for recipe conflicts, even if temporarily. Can also output a list of recipe conflicts for some crafty tweaking later.

_Polymorph is a mod that solves recipe conflicts by letting players choose between all potential outputs shared by the same ingredients._

**Comment by karlreinert** [comment] 2020-07-20 17:29
https://www.curseforge.com/minecraft/mc-mods/botany-pots
       and bonsai trees when it gets bumped up.

https://www.curseforge.com/minecraft/mc-mods/tesseract
        and flux network when it gets a bump up:D

https://www.curseforge.com/minecraft/mc-mods/productivebees
       also cows and chickens... I prefer this method over mining.

https://www.curseforge.com/minecraft/mc-mods/teleportmod
      WARNING: HAvent actually tested this one.. And I cant really say I noticed any other teleportation mod in the pack as of now.

**Comment by florensie** [comment] 2020-07-21 12:20
[Artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts)
Requires [Curios](https://www.curseforge.com/minecraft/mc-mods/curios) if it isn't in already.

**Comment by karlreinert** [comment] 2020-07-21 14:40
https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension

Mining DIm...

**Comment by Mowmaster** [comment] 2020-07-21 17:35
https://www.curseforge.com/minecraft/mc-mods/pedestals

Mainly for item transport (can transfer 64items/tick)
Its also really good for a lot of different farm types.

**Comment by daniel124356** [comment] 2020-07-22 18:15
Can we add openblocks elevator please its been updated to 1.16 https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator/files

**Comment by WhitePhant0m** [comment] 2020-07-22 18:38
> 
> 
> Can we add openblocks elevator please its been updated to 1.16 https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator/files

We already have it?

**Comment by ShayBox** [comment] 2020-07-25 03:39
https://www.curseforge.com/minecraft/mc-mods/durability101

**Comment by ESTD3** [comment] 2020-07-25 07:25
https://www.curseforge.com/minecraft/mc-mods/botany-pots

**Comment by ESTD3** [comment] 2020-07-25 07:29
https://www.curseforge.com/minecraft/mc-mods/productivebees works really well with buzzier bees, please add :)

**Comment by daniel124356** [comment] 2020-07-25 07:50
Biomes o plenty, self explanatory i think :)
https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty

**Comment by PrfessionalWeeb** [comment] 2020-07-25 20:13
[Building Wands](https://www.curseforge.com/minecraft/mc-mods/building-wands)

A builders wand would be really useful, especially for building big mekanism multiblocks.

**Comment by ClaudiusMinimus** [comment] 2020-07-25 20:50
- https://www.curseforge.com/minecraft/mc-mods/polymorph For duplicate recipes
- https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension
- https://www.curseforge.com/minecraft/mc-mods/silents-gems One of my favorites with Silent Gear
- https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension

**Comment by ESTD3** [comment] 2020-07-26 12:26
https://www.curseforge.com/minecraft/mc-mods/pedestals
https://www.curseforge.com/minecraft/mc-mods/botany-pots
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3014795
https://www.curseforge.com/minecraft/mc-mods/anvil-fix
https://www.curseforge.com/minecraft/mc-mods/flora-doubling
https://www.curseforge.com/minecraft/mc-mods/rftools-base all of the mcjty mods are nice :)

**Comment by florensie** [comment] 2020-07-26 23:44
[Egg Tab](https://www.curseforge.com/minecraft/mc-mods/eggtab-forge)

**Comment by family1242** [comment] 2020-07-27 14:41
https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge
A really fun mod.

**Comment by EpicMiner57** [comment] 2020-07-28 23:44
[https://www.curseforge.com/minecraft/mc-mods/azuredooms-angel-ring] but replace the gold with something else

**Comment by Dartherez1234** [comment] 2020-08-01 22:05
[Silents Gems](https://www.curseforge.com/minecraft/mc-mods/silents-gems)

**Comment by Conspectral** [comment] 2020-08-02 04:44
[https://www.curseforge.com/minecraft/mc-mods/towers-of-the-wild](Towers of the Wild)

Seems like a fun additional worldgen structure spawn that (seems) to be compatible with BoP when its fully 1.16-ready. Any extra exploration points seem kinda neat.

**Comment by paulspchelp-au** [comment] 2020-08-02 06:37
https://www.curseforge.com/minecraft/mc-mods/lightest-lamps  one of best mods   in mod pack  can i be put back in  pls

**Comment by omarmartinez97** [comment] 2020-08-03 17:24
https://www.curseforge.com/minecraft/mc-mods/azuredooms-chunk-loader; maybe change the recipe to require crafting plus/powah's infusing and lots of energy

**Comment by Ars2014** [comment] 2020-08-04 10:16
https://www.curseforge.com/minecraft/mc-mods/ftb-backups
Also, as Lat said, FTB Chunks will be released on CF soon.

**Comment by AlexisLSX** [comment] 2020-08-05 01:16
https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture

**Comment by BarryBlackCat** [comment] 2020-08-05 19:00
https://www.curseforge.com/minecraft/mc-mods/macaws-roofs
I'm terrible at building roofs xd

**Comment by Ars2014** [comment] 2020-08-06 14:01
https://jenkins.latmod.com/job/FTB-Chunks/19/

**Comment by Halloxe** [comment] 2020-08-07 03:58
https://www.curseforge.com/minecraft/mc-mods/cyclic

**Comment by Ars2014** [comment] 2020-08-07 12:16
@whatthedrunk, FastWorkbench and Toast Control got updates, so they can work with new Forge.

**Comment by Fuffled-Fuffles** [comment] 2020-08-07 14:06
https://www.curseforge.com/minecraft/mc-mods/just-another-head-mod-jahm

**Comment by CapitanCJ** [comment] 2020-08-07 20:19
https://www.curseforge.com/minecraft/mc-mods/enderthing

**Comment by OneLemonyBoi** [comment] 2020-08-08 03:38
https://www.curseforge.com/minecraft/mc-mods/simpleharvest

**Comment by omarmartinez97** [comment] 2020-08-08 21:13
https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-vehicle-mod 
a fun one

**Comment by Snips-xc** [comment] 2020-08-10 04:04
Thaumcraft 6. 
https://www.curseforge.com/minecraft/mc-mods/thaumcraft

**Comment by cech12** [comment] 2020-08-11 08:39
Useful Hats
https://www.curseforge.com/minecraft/mc-mods/useful-hats

**Comment by davethwave** [comment] 2020-08-11 18:34
https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension
Mining in a server with a mod like this would be helpful for community bases.

**Comment by mrdeadlocked** [comment] 2020-08-14 23:51
Cyclic
https://www.curseforge.com/minecraft/mc-mods/cyclic

**Comment by bessiq** [comment] 2020-08-15 18:06
Macaw's Trapdoors - might as well complete the collection.
https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors

SwingThroughGrass - because grass can't stop swords!
https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass

**Comment by CorgiTaco** [comment] 2020-08-15 23:01
https://www.curseforge.com/minecraft/mc-mods/better-weather

**Comment by CamT29** [comment] 2020-08-16 00:34
https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod

**Comment by CamT29** [comment] 2020-08-16 16:02
https://www.curseforge.com/minecraft/mc-mods/building-gadgets

**Comment by CapitanCJ** [comment] 2020-08-20 17:24
https://www.curseforge.com/minecraft/mc-mods/tinkers-mechworks

**Comment by omarmartinez97** [comment] 2020-08-25 01:52
https://www.curseforge.com/minecraft/mc-mods/electrodynamics
gives more possibilities of endgame RF generation besides mekanism's reactors and other utilities like forcefields

**Comment by Ironskullmedia** [comment] 2020-08-27 01:33
https://www.curseforge.com/minecraft/mc-mods/botany-pots

**Comment by LotuxPunk** [comment] 2020-08-28 15:51
Hello ! May I suggest some mods for 1.16.2 ?
https://www.curseforge.com/minecraft/mc-mods/pollinator
https://www.curseforge.com/minecraft/mc-mods/nicephore

**Comment by Tbizla** [comment] 2020-08-28 23:43
> https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension
> Mining in a server with a mod like this would be helpful for community bases.

^ Just updated for 1.16.2

**Comment by Tbizla** [comment] 2020-08-29 01:36
Solar gen

https://www.curseforge.com/minecraft/mc-mods/solargeneration

**Comment by Tbizla** [comment] 2020-08-29 14:59
Rotten flesh to leather

https://www.curseforge.com/minecraft/mc-mods/just-another-rotten-flesh-to-leather-mod

**Comment by Tbizla** [comment] 2020-08-30 13:30
This could be interesting

https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod

**Comment by CaptainBrineybeard** [comment] 2020-08-31 19:55
Thoughts on adding Enigmatic Legacy to ATM 6? Pretty simple mod, just adds some fun end-game/dungeon loot accessories to the game. Provides alternatives to flight at a cost (requires a beacon, and drains experience), a set of endgame armor and tools, among other things.

https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy

**Comment by MelanX** [comment] 2020-09-03 15:40
[Botanical Machinery](https://www.curseforge.com/minecraft/mc-mods/botanical-machinery)

**Comment by TelepathicGrunt** [comment] 2020-09-04 17:34
https://www.curseforge.com/minecraft/mc-mods/blame
Add extra info to crashlogs to make finding the mod responsible for the crashing features/structures much easier (vanilla is missing said info to know which mod to feature it is)

**Comment by flamingram** [comment] 2020-09-05 05:25
Mod suggestion/ replacement 
Resourceful bees to be replaced with productive bees 
Less buggy 
https://www.curseforge.com/minecraft/mc-mods/productivebees

**Comment by Epic428** [comment] 2020-09-05 07:19
> Mod suggestion/ replacement
> Resourceful bees to be replaced with productive bees
> Less buggy
> https://www.curseforge.com/minecraft/mc-mods/productivebees

Would be nice to know the bugs being referred to. It’s difficult to fix unknown bugs without issue/bug reports. And the bugs that do get reported get fixed.

**Comment by Crimix** [comment] 2020-09-05 12:21
[ServerTabInfo](https://www.curseforge.com/minecraft/mc-mods/server-tab-info) updated for 1.16.2

**Comment by flamingram** [comment] 2020-09-05 16:56
> > Mod suggestion/ replacement
> > Resourceful bees to be replaced with productive bees
> > Less buggy
> > https://www.curseforge.com/minecraft/mc-mods/productivebees
> 
> Would be nice to know the bugs being referred to. It’s difficult to fix unknown bugs without issue/bug reports. And the bugs that do get reported get fixed.

Baby bees I believe in the productive bee mod don’t die to growing up and or flying away due to roof aswell as the hives work with vanilla bees

**Comment by Tbizla** [comment] 2020-09-05 20:04
Curios support for Iron Jetpacks

https://www.curseforge.com/minecraft/mc-mods/curious-jetpacks

**Comment by Epic428** [comment] 2020-09-06 00:04
> > > Mod suggestion/ replacement
> > > Resourceful bees to be replaced with productive bees
> > > Less buggy
> > > https://www.curseforge.com/minecraft/mc-mods/productivebees
> > 
> > 
> > Would be nice to know the bugs being referred to. It’s difficult to fix unknown bugs without issue/bug reports. And the bugs that do get reported get fixed.
> 
> Baby bees I believe in the productive bee mod don’t die to growing up and or flying away due to roof aswell as the hives work with vanilla bees

Child bees dying due to growing up when beneath a block is a vanilla issue. It would affect vanilla bees and productive bees as well. The only way to fix it would be to add complex logic handling a one-off case. Our hives not working with vanilla bees was a design choice. Not a bug. I can easily change that and very likely will given the number of requests. Currently our focus is on overhauling the core code structure for 1.16.2 to support dynamic registration and improve mod integrations.

**Comment by kaladaran** [comment] 2020-09-07 19:14
https://www.curseforge.com/minecraft/mc-mods/elemental-craft

**Comment by flamingram** [comment] 2020-09-08 01:13
https://www.curseforge.com/minecraft/mc-mods/silents-gems 
good addon for silent gear

**Comment by stillg0ld** [comment] 2020-09-09 00:07
I would love to see some new structure gen mods in this pack. 

Dungeon Crawl (based very closely to the roguelike dungeons mod of 1.12)
Dungeons Plus
Towers of the Wild
Valhelsia Structures

**Comment by stillg0ld** [comment] 2020-09-09 00:11
The reed height in the Apotheosis config by default seems to be a typo. Bamboo is set to 32, cactus was upped to 5 while reed height was upped to 255. It makes farming a very laggy experience. Personally, I feel like 5 or even 7 sugarcane reeds is plenty. Not 100% certain but didn't seem to be intentional.

**Comment by Epic428** [comment] 2020-09-09 22:53
apotheosis is known for world height sugarcane. not a typo

**Comment by bessiq** [comment] 2020-09-10 19:54
https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings

**Comment by naqaden** [comment] 2020-09-13 19:46
Resubmitting [Name Pain](https://www.curseforge.com/minecraft/mc-mods/name-pain/) after an update added more visibility options, newer 1.16.x support, and some compatibility/fixes.

**Comment by naqaden** [comment] 2020-09-13 19:46
Resubmitting [Name Pain](https://www.curseforge.com/minecraft/mc-mods/name-pain/) after an update added more visibility options, newer 1.16.x support, and some compatibility/fixes.

**Comment by Edivad99** [comment] 2020-09-14 07:29
https://www.curseforge.com/minecraft/mc-mods/fluidsystem

**Comment by BLumbye** [comment] 2020-09-14 09:17
Solar Flux Reborn: https://www.curseforge.com/minecraft/mc-mods/solar-flux-reborn
Charging Gadgets: https://www.curseforge.com/minecraft/mc-mods/charging-gadgets
Building Gadgets: https://www.curseforge.com/minecraft/mc-mods/building-gadgets
Cyclic: https://www.curseforge.com/minecraft/mc-mods/cyclic

**Comment by cauanmendonca** [comment] 2020-09-15 08:33
[Deep Mob Learning](https://www.curseforge.com/minecraft/mc-mods/deep-mob-learning-refabricated)

**Comment by cauanmendonca** [comment] 2020-09-15 08:38
RFTools already came out to 1.16 version
[Base](https://www.curseforge.com/minecraft/mc-mods/rftools-base)
[Utility](https://www.curseforge.com/minecraft/mc-mods/rftools-utility)
[Power](https://www.curseforge.com/minecraft/mc-mods/rftools-power)
[Builder](https://www.curseforge.com/minecraft/mc-mods/rftools-builder)
[Storage](https://www.curseforge.com/minecraft/mc-mods/rftools-storage)
[Control](https://www.curseforge.com/minecraft/mc-mods/rftools-control)

**Comment by cauanmendonca** [comment] 2020-09-16 08:39
the chests can be combined vertically or on either horizontal axis with this mod, because this i realy recommend replace the iron chests an the recipes are the same.
[Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge)

**Comment by cauanmendonca** [comment] 2020-09-16 08:43
[beenfo](https://www.curseforge.com/minecraft/mc-mods/beenfo)

**Comment by Epic428** [comment] 2020-09-16 10:00
> beenfo

@cauanmendonca 

I didn’t realize that mod existed. I’ll be sure to add that information to our hives and since I’m using mixin for vanilla stuff I’ll see if I could possibly add it to the vanilla hives/nests as well.

**Comment by cauanmendonca** [comment] 2020-09-16 21:45
[Repurposed Structures](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)

**Comment by cauanmendonca** [comment] 2020-09-17 05:27
[Enchantments Reloaded](https://www.curseforge.com/minecraft/mc-mods/enchantments-reloaded)

**Comment by mrgreaper** [comment] 2020-09-17 13:48
[age-of-exile](https://www.curseforge.com/minecraft/mc-mods/age-of-exile) Diablo like loot and class based magic system, sounds fun 1.16.1 and 1.16.3

**Comment by cauanmendonca** [comment] 2020-09-18 06:39
While Tinker's Construct does not come to version 1.16 we can use this mod that brings only his table.
[Crafting Station
](https://www.curseforge.com/minecraft/mc-mods/crafting-station)

**Comment by cauanmendonca** [comment] 2020-09-18 06:40
[Greater Eye of Ender](https://www.curseforge.com/minecraft/mc-mods/greater-eye-of-ender-forge)

**Comment by cauanmendonca** [comment] 2020-09-18 06:44
[Easy Villagers
](https://www.curseforge.com/minecraft/mc-mods/easy-villagers)

**Comment by cauanmendonca** [comment] 2020-09-18 06:47
[Lava Monsters](https://www.curseforge.com/minecraft/mc-mods/lava-monsters)

**Comment by cauanmendonca** [comment] 2020-09-18 06:51
[Bee Keeper](https://www.curseforge.com/minecraft/mc-mods/beekeeper)

**Comment by cauanmendonca** [comment] 2020-09-18 06:55
[Farlanders](https://www.curseforge.com/minecraft/mc-mods/farlanders)

**Comment by cauanmendonca** [comment] 2020-09-18 17:46
[Item Collectors
](https://www.curseforge.com/minecraft/mc-mods/item-collectors)

**Comment by cauanmendonca** [comment] 2020-09-18 21:34
[RevampedWolf](https://www.curseforge.com/minecraft/mc-mods/revampedwolf)

**Comment by cauanmendonca** [comment] 2020-09-18 21:37
Builder Wands 1.16
[Construction Wand](https://www.curseforge.com/minecraft/mc-mods/construction-wand)

**Comment by cauanmendonca** [comment] 2020-09-18 21:42
Ported to 1.16
[Dwarf Coal](https://www.curseforge.com/minecraft/mc-mods/dwarf-coal)

**Comment by Firenzeo** [comment] 2020-09-19 00:47
> Builder Wands 1.16
> [Construction Wand](https://www.curseforge.com/minecraft/mc-mods/construction-wand)

Obsoleted by Building Gadgets.

**Comment by CrankySupertoon** [comment] 2020-09-20 12:42
> > Builder Wands 1.16
> > [Construction Wand](https://www.curseforge.com/minecraft/mc-mods/construction-wand)
> 
> Obsoleted by Building Gadgets.

Builders wands and building gadgets work differently. i prefer the wands

**Comment by cauanmendonca** [comment] 2020-09-20 19:25
[Double Doors](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[SecurityCraft](https://www.curseforge.com/minecraft/mc-mods/security-craft)

**Comment by cauanmendonca** [comment] 2020-09-20 22:49
[Extra Anvils
](https://www.curseforge.com/minecraft/mc-mods/extra-anvils)

**Comment by cauanmendonca** [comment] 2020-09-20 22:53
With this mod we don't really need one arrow in the bag to use the infinity enchant on the bow
[Bow Infinity Fix](https://www.curseforge.com/minecraft/mc-mods/bow-infinity-fix)

**Comment by cauanmendonca** [comment] 2020-09-20 22:55
With this mod we can store the experience in bottles
[Exp Bottling](https://www.curseforge.com/minecraft/mc-mods/exp-bottling)

**Comment by mrgreaper** [comment] 2020-09-21 22:26
Ichun has been back at it :)

[Attachable grinders](https://www.curseforge.com/minecraft/mc-mods/attachable-grinder)
place grinder on mob, watch as the drops are pushed out :) 

[Clef](https://www.curseforge.com/minecraft/mc-mods/clef)
Clef adds instruments that can play abc files (think starbound) there is nothing like this in minecraft and could be great fun for players on a server

[Shatter](https://www.curseforge.com/minecraft/mc-mods/shatter) 
Client side mod that makes mobs shatter on death, way cooler than the default death animation

**Comment by mrgreaper** [comment] 2020-09-23 20:59
[Simple Planes](https://www.curseforge.com/minecraft/mc-mods/simple-planes)
Flyable planes in minecraft :)

**Comment by Firenzeo** [comment] 2020-09-24 15:21
> [Simple Planes](https://www.curseforge.com/minecraft/mc-mods/simple-planes)
> Flyable planes in minecraft :)

Have it on my server, it's quite stable, and as the name implies, simple.

**Comment by JulianEisner** [comment] 2020-09-25 07:07
[Embellish Craft](https://www.curseforge.com/minecraft/mc-mods/embellishcraft)

This would be a great decoration mod, including some nice new block textures for vanilla and add mod based blocks. It's also adding some interior decoration blocks/items ;)

**Comment by Commoble** [comment] 2020-09-26 12:52
[Bag of Yurting](https://www.curseforge.com/minecraft/mc-mods/bag-of-yurting)

**Comment by Commoble** [comment] 2020-09-26 22:13
[Clockout](https://www.curseforge.com/minecraft/mc-mods/clockout)
[Entity Detectors](https://www.curseforge.com/minecraft/mc-mods/entity-detectors)

**Comment by P3pp3rF1y** [comment] 2020-09-29 19:36
A bit of a self promotion, but you tended to include the mod in your previous versions of the modpack :) 

[Reliquary](https://www.curseforge.com/minecraft/mc-mods/reliquary-v1-3) now updated to 1.16.3

**Comment by cauanmendonca** [comment] 2020-09-30 17:47
Improves the vanilla spiders
[Spiders 2.0](https://www.curseforge.com/minecraft/mc-mods/spiders-2-0)

Better crafters to Refined Storage ( Beta Version ) 
[ExtraStorage](https://www.curseforge.com/minecraft/mc-mods/extrastorage)

Life improvement...
[Path Under Gates](https://www.curseforge.com/minecraft/mc-mods/path-under-gates)

**Comment by Edivad99** [comment] 2020-10-01 12:57
An addon for Refined Storage: [ExtraStorage](https://www.curseforge.com/minecraft/mc-mods/extrastorage)

**Closed** 2020-10-01 17:30 UTC

**Comment by Commoble** [comment] 2020-10-02 01:20
[Jumbo Furnace](https://www.curseforge.com/minecraft/mc-mods/jumbo-furnace)

**Comment by karlreinert** [comment] 2020-10-26 15:34
Flux Networks
Prefab
Simple Storage Network
