### ISSUE TITLE
[Bug]: Engineer's Hammer cannot make metal plates unless it has full durability

### ISSUE THREAD

**Issue by SamDDBS** [AllTheMods/ATM-6#2471] opened 2021-10-01 00:16 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

read title
![image](https://user-images.githubusercontent.com/72839318/135546866-85d2faf8-0db1-4046-8afa-5a19ad7103dd.png)

### latest.log

n/a

**Comment by ladylexxie** [comment] 2021-10-01 00:33
Duplicate of #2456

**Closed by ladylexxie** 2021-10-01 00:33 UTC
Labels: Bug
