### ISSUE TITLE
Server Crashed when player was attacked by Endermite.

### ISSUE THREAD

**Issue by ovingiv** [AllTheMods/ATM-6#374] opened 2020-11-24 05:10 UTC
**Describe the bug**
Player was attacked by Endermite when having an enchantment on armor that teleports enemies when you get hurt by them. 

**To Reproduce**
1. Go to The End
2. Confirm you have enchantment which teleports enemies away when getting attacked by them.
3. Spawn/find Endermite and get hit by them.
4. See Crash Report.

**Expected behavior**
Either player or Endermite gets teleported.

**Additional context**
Crash Logs: 
https://pastebin.com/t48pEmZV
https://pastebin.com/LFD8tREP

This is for version of ATM6 1.16.3 - 1.2.0

**Comment by ViRb3** [comment] 2020-11-24 11:21
Can you try to nail down the exact enchantment (and the mod which if comes from) that causes the crash?

**Comment by ovingiv** [comment] 2020-11-24 21:50
> Can you try to nail down the exact enchantment (and the mod which it comes from) that causes the crash?

Yup I had to roll back the server an hour and waiting for my friend to get back to me what enchantments they have.

**Comment by ovingiv** [comment] 2020-11-28 02:50
He has Displacement Level 5 enchantment from the mod Ensorcellation which causes enemies to be teleported away.

**Comment by ViRb3** [comment] 2020-11-28 12:36
So with just `Displacement 5`, the game crashes when player was attacked by Endermite?

**Comment by ovingiv** [comment] 2020-11-28 14:32
Correct.

**Comment by ovingiv** [comment] 2020-11-30 03:34
> So with just `Displacement 5`, the game crashes when player was attacked by Endermite?

Yes.

**Comment by D3s0l4ti0n** [comment] 2020-12-08 18:49
I've had this issue on my server and when it happens I have them login and as soon as it says they loved in I to them to me and it fixes the issue you gotta be fast thou before all the chunks around them load

**Comment by ViRb3** [comment] 2020-12-22 00:29
Following a conversation with the dev of Ensorcellation, the issue is that Displacement _should_ be limited to level 3, but Apotheosis allows it to reach level 5 (and beyond), which causes Endermites to be sent so far away that they go in a unloaded chunk, which causes a crash. A fix will be pushed soon, and ATM6 will update when that happens.

**Comment by ViRb3** [comment] 2020-12-25 00:39
Upon further investigation, it seems like the issue is not with Apotheosis and Ensorcellation. If you have only these two mods, there's no crash. It's probably another mod that uses a mixin to inject code at the same time as the Displacement enchantment distance is calculated. I am working on a tool to list all such mixins so I can debug this issue better.

**Comment by ovingiv** [comment] 2020-12-25 01:48
I would be glad to help if you would like.

**Comment by ViRb3** [comment] 2020-12-25 01:51
@ovingiv If you can figure out which mod causes Ensorcellation to crash that would be ideal.

**Comment by whatthedrunk** [comment] 2021-01-16 01:31
I believe this is fixed in 1.4.0 let us know if its still an issue

**Comment by Karinth** [comment] 2021-03-23 18:54
So this still happens in 1.5.4b Is there a fix for it yet or a way to disable endermites at all?

**Comment by matijas1** [comment] 2021-04-21 22:58
Ye this definitely still happens

**Comment by Shadowgar** [comment] 2021-04-25 00:21
This just crashed our server tonight. My armor has Displacement.

https://pastebin.com/sGWrBS9v

**Closed** 2021-06-08 08:06 UTC
Labels: Bug, Mod Issue
