### ISSUE TITLE
Unable to go to Nether after 1.16.3 update

### ISSUE THREAD

**Issue by anniemoose98** [AllTheMods/ATM-6#137] opened 2020-09-24 03:45 UTC
Hi all! 

I have a multiplayer world I generated on your 1.16.2 build that I updated to 1.16.3 yesterday. After the update, players can no longer teleport to the Nether. The animation on the portal continues ad naseum and manually teleporting via /execute results in the server saying that Minecraft:the_nether is unknown. I attempted to delete DIM-1 and DIM in the world files to force the Nether to regenerate manually, but the issue persists.

**Comment by Revvilo** [comment] 2020-09-27 21:52
Check your level.dat for your world. Under `WorldGenSettings > dimensions` as mine seemed to be missing the nether and end entries.
I made a server on the stable version of atm6 for my friends using my existing world which was generated in the beta version and found the same issue.
If this is your issue, I would recommend generating a new world, opening the level.dat in [NBTExplorer](https://github.com/jaquadro/NBTExplorer), and copying the end and nether entries from the new `dimensions` tag into the corresponding `dimensions` tag within the offending level.dat. (There are copy and paste buttons at the top of NBTExplorer. Just open two windows, with one level.dat in each window)

![image](https://user-images.githubusercontent.com/13816212/94376339-7ecc0280-0176-11eb-9a68-343aadc06b3f.png)

**Comment by Jkwolf25** [comment] 2020-10-08 17:48
A bit of warning when doing this on a world that has been previously generated. I followed the directions given above and it did restore my Nether, but then I decided to reset my Nether and... I now have Rainbow hills biome in the Nether... Overworld music, grass with flowers, tons of bats, and... WATER... yep, water can spawn in the nether? I dont think this is intended, it also affects ore spwaning, so no gold, no crimson iron, and no quartz, no vibrainium. No mob spawns either? Here are a couple screenies. In the areas that are nether biomes, it works as intended, but I think moving that .DAT info over from a new world may have had some unintended side effects. ( I believe this is a conflict with Biomes of Plenty and OH, the Biomes You'll Go!)

![2020-10-08_12 11 19](https://user-images.githubusercontent.com/48677976/95495042-75a41800-0964-11eb-9c58-f15d237fd4cf.png)

![2020-10-08_12 10 49](https://user-images.githubusercontent.com/48677976/95494968-5dcc9400-0964-11eb-8c56-afbb55e9b988.png)

**Comment by Revvilo** [comment] 2020-10-08 18:14
That's baffling... I'm not super familiar yet with the format of the level.dat, but I'm suspicious that this might be due to a generator type setting within it elsewhere. I will be afk for a day ish, so until then you could generate a fresh world and see if you can find any differences relating to the nether between it and your current world, as that would be where I would start.
Sorry about messing up your world 🥺

**Comment by Cntrldfusion** [comment] 2020-10-08 18:30
A note to Mac users, NBT Edit has not been updated to work on any version that does not support 32-bit (10.14 and up).

**Comment by Jkwolf25** [comment] 2020-10-09 12:55
> Sorry about messing up your world 🥺

Don't worry! I just started fresh. I packed up my valuables and migrated player inventory to the new world. (Crimson iron ore was not included in "All the Ores" mod so I needed to refresh the Nether to get some. Similarly I was in the process of packing up my base to move to another location anyhow so the transition was easily made)

**Comment by ashk0re** [comment] 2020-10-24 16:41
I have a similar problem. I started a complete new game on a dedicated server with your release of ATM6 MC 1.16.3 Version. Newest version is installed. Level.dat looks fine. Nether is generated. If i build a portal, i can use it one time. Nether looks fine. If i use the portal a second time, then i get a port loop. And it is really really difficult to leave the loop.

In console it spams:

[18:20:58] [Server thread/WARN] [minecraft/ServerPlayNetHandler]: XXXXXXX moved too quickly! 3756.532369292392,5.5,-558.6984571581646
[18:20:59] [Netty Epoll Server IO #4/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@65464f69 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[18:20:59] [Netty Epoll Server IO #4/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@2b8aca83 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!

if someone uses the portal. 

If i destroy the portal and rebuild it, then again the first usage is ok. 
I have no idea where the problem is ..... already looked at several configs etc.

**Comment by AmuHeart** [comment] 2020-11-02 08:12
can confirm, first use works per individual player, after that it only causes a loop and gets players stuck in blocks, as if they're being pulled through the ground to the position of the portal.
it was a LAN game on my end and client keeps pushing following whenever the portal is being entered (note it behaved in a way that made you go to the nether and instantly looped you back to the overworld without looping again, had a permanent loop happen before too tho):

[21:56:06] [Netty Client IO #5/ERROR]: Could not deserialize minecraft:
[21:56:06] [Netty Client IO #5/ERROR]: Could not deserialize minecraft:
[21:56:06] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[21:56:10] [Render thread/FATAL]: Error executing task on Client
java.lang.IndexOutOfBoundsException: null
	at io.netty.buffer.EmptyByteBuf.readUnsignedByte(EmptyByteBuf.java:536) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.network.PacketBuffer.readUnsignedByte(PacketBuffer.java:759) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:155) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2907/949732051.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2909/2078175306.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:76) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$20533/2122399736.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:76) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1902) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$20846/309411720.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.25.jar:34.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$464/1896539815.call(Unknown Source) [forge-1.16.3-34.1.25.jar:34.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?]

**Comment by thnders** [comment] 2020-11-15 01:47
I can confirm this issue is still open today. Running ATM6 1.3.0. 

Things I attempted that didn't succeed:
- Deleting DIM-1
- Remaking the portal
- Making a new portal several hundred blocks away
- Using someone else's existing portal (several hundred blocks away from initial portal trial)

As of 1.3.0 I receive no error messages. Available to show loop on discord if necessary Thunder#5621

**Comment by thevortex** [comment] 2020-11-15 02:15
following Revillo's example above will get you past this issue, this is a forge bug that has only recently been fixed, the next version of ATM 6 should hopefully be free of this nbt corruption

**Comment by Kris1432** [comment] 2020-11-15 10:24
@thevortex does that mean all the biomes won't be messed up in the next version of the modpack? Or just referencing the Nether/End travel problem?

**Comment by ViRb3** [comment] 2020-11-15 16:44
Here's another graphic explaining the same procedure:

![image](https://user-images.githubusercontent.com/2650170/99191008-9ab15500-2772-11eb-8675-0ed2da3d29d4.png)

**Comment by Shadowmuse** [comment] 2020-11-17 00:39
I was having the same issue.

Deleting both the level.dat and level.dat_old and allowing them to be remade on next server launch without any other modifications seems to have fully resolved the issue.

Several hours of additional gameplay so far and quite a lot of chunk generation has revealed no issues.
(I have limited experience with these files compared to Revillo above, so always make a back up before trying this if his method creates any issues).

**Comment by NoMoreStars** [comment] 2020-11-20 00:45
Seems like copying over the dimensions over from the same seed results in some weirdness with the biomes even without resetting the dimensions. For instance, what was once a Glowstone Garden biome is now shown as a Rocky Beach biome, including the spawning of overworld hostile mobs rather than the Piglins and Zombie Piglins that typically spawn there. Luckily I backed up my save before I copied the nether and end files over. Hope someone finds a fix that doesn't involve having to start a world from scratch and losing all my progress lol.

![2020-11-19_18 34 56](https://user-images.githubusercontent.com/38673759/99741491-e9266280-2a96-11eb-84c0-c2733630d04c.png)

**Comment by ViRb3** [comment] 2020-11-20 01:14
I can actually confirm the observation above. I did `/locatebiome minecraft:swap` and teleported to the coords, only to find it was a completely different biome with no swamp nearby.

**Comment by Beano8U** [comment] 2020-11-23 08:56
Thanks Revvilo 👍 
Seemed to work. I used the seed shown from my current world to create a new one, but it seems the biome I spawned in on the new world may have been different for some reason.
Still worked and all my tunnels and map data was still there in the Nether even. I was expecting it to be all fresh.
Bit odd to find a plague doctor in there though haha.
Cheers for the info and fix 👍

**Comment by Najiro11** [comment] 2020-11-23 19:26
> A bit of warning when doing this on a world that has been previously generated with Oh, The Biomes Youll Go. I followed the directions given above and it did restore my Nether, but then I decided to reset my Nether and... I now have Rainbow hills biome in the Nether... Overworld music, grass with flowers, tons of bats, and... WATER... yep, water can spawn in the nether? I dont think this is intended, it also affects ore spwaning, so no gold, no crimson iron, and no quartz, no vibrainium. No mob spawns either? Here are a couple screenies. In the areas that are nether biomes, it works as intended, but I think moving that .DAT info over from a new world may have had some unintended side effects. ( I believe this is a conflict with Biomes of Plenty and OH, the Biomes You'll Go!)
> 
> ![2020-10-08_12 11 19](https://user-images.githubusercontent.com/48677976/95495042-75a41800-0964-11eb-9c58-f15d237fd4cf.png)
> 
> ![2020-10-08_12 10 49](https://user-images.githubusercontent.com/48677976/95494968-5dcc9400-0964-11eb-8c56-afbb55e9b988.png)

When doing this, i cant open my world anymore... After several times of trying it. 

Just warning other ppls, that it might happend.

**Comment by Najiro11** [comment] 2020-11-23 19:29
> Check your level.dat for your world. Under `WorldGenSettings > dimensions`, mine seemed to be missing the nether and end entries.
> I made a server on the stable version of atm6 for my friends using my existing world which was generated in the beta version and found the same issue.

When i did it, i cant open my world anymore... When i click on my world it infinitely loads but never load. After 4 hours of trying to get it work i gave up.

And im warning other ppls that it might happen to them too.
> If this is your issue, I would recommend generating a new world, opening the level.dat in [NBTExplorer](https://github.com/jaquadro/NBTExplorer), and copying the end and nether entries from the new world level.dat into the corresponding `dimensions` tag within the offending level.dat. (There are copy and paste buttons at the top of NBTExplorer. Just open two windows, with one level.dat in each window)
> 
> I should note that if you have custom settings for your broken world, it's probably best to generate the new world with those settings. Things like the world generator setting and all that.
> 
> ![image](https://user-images.githubusercontent.com/13816212/94376339-7ecc0280-0176-11eb-9a68-343aadc06b3f.png)



When i did it, i cant open my world anymore... When i click on my world it infinitely loads but never load. After 4 hours of trying to get it work i gave up.

And im warning other ppls that it might happen to them too.

**Comment by ViRb3** [comment] 2020-11-24 14:22
This should have been fixed in ATM 1.3.2 via Forge's update: https://github.com/MinecraftForge/MinecraftForge/pull/7445. Please comment here if still experiencing it.

**Comment by ViRb3** [comment] 2020-11-28 12:48
Please check the issue linked above for a solution.

**Closed** 2020-11-28 12:49 UTC
Labels: Bug, Reported

**Comment by ProxyNeko** [comment] 2021-01-18 17:28
Evening all, I dropped by your discord server earlier today and was directed to this issue, I've a simpler fix in the form of a mod from another mod developer with the MMD discord server called [dimension scalpel](https://www.curseforge.com/minecraft/mc-mods/dimension-scalpel) this mod did the trick flawlessly for me and to save a headache for anyone who may have the same issues in the future I thought I'd share it. (Although I seem to be late to the party haha)

**Comment by ViRb3** [comment] 2021-01-19 00:56
This mod didn't exist back when we started dealing with this issue, and a fix has now been included in Forge, so hopefully this issue will be dead for good. Thanks for sharing though, it may help people upgrading between old versions.
