### ISSUE TITLE
Missing Texture - Silent Gear & Nature's Aura

### ISSUE THREAD

**Issue by PopcraftReal** [AllTheMods/ATM-6#174] opened 2020-10-15 11:14 UTC
**Describe the bug**
* In the screenshots *
The "nature's aura"'s manual and some Silent Gear's tools like armours and tips are missing the texture.

**To Reproduce**
1. Craft a Nature's Aura's manual or craft a piece of armours using Vanilla's

**Expected behavior**
Having proper textures

**Screenshots**
![Screenshot 2020-10-15 220608](https://user-images.githubusercontent.com/72920999/96116145-bb984780-0f33-11eb-88a3-db1992abc24d.png)

![Screenshot 2020-10-15 220541](https://user-images.githubusercontent.com/72920999/96116141-b9ce8400-0f33-11eb-92d8-b12b97e2632e.png)

**Comment by Odey555** [comment] 2020-10-19 16:20
Thought I'd add in a few others I've found. Ars Nouveau, Pneumaticraft, Bigger Reactors, Forbidden & Arcanus, Pedestals, Phosphophillite, and Woot 

![image](https://user-images.githubusercontent.com/1361563/96477651-2637d480-120d-11eb-8dbc-a0bcc3c6c049.png)
![image](https://user-images.githubusercontent.com/1361563/96477726-3a7bd180-120d-11eb-93d2-11b26a7d1bd6.png)
![image](https://user-images.githubusercontent.com/1361563/96477748-3f408580-120d-11eb-8dad-269c0db7d6e1.png)
![image](https://user-images.githubusercontent.com/1361563/96477773-44053980-120d-11eb-9e3c-b56a42ac857a.png)
![image](https://user-images.githubusercontent.com/1361563/96477785-48c9ed80-120d-11eb-9b15-1aa7de4a841c.png)
![image](https://user-images.githubusercontent.com/1361563/96478096-a827fd80-120d-11eb-8415-ee64cf3e1bab.png)
![image](https://user-images.githubusercontent.com/1361563/96478188-c2fa7200-120d-11eb-8814-8986a3c16952.png)

**Comment by WhitePhant0m** [comment] 2020-10-19 16:29
> 
> 
> Thought I'd add in a few others I've found. Ars Nouveau, Pneumaticraft, Bigger Reactors, Forbidden & Arcanus, Pedestals, Phosphophillite, and Woot
> 
> ![image](https://user-images.githubusercontent.com/1361563/96477651-2637d480-120d-11eb-8dbc-a0bcc3c6c049.png)
> ![image](https://user-images.githubusercontent.com/1361563/96477726-3a7bd180-120d-11eb-93d2-11b26a7d1bd6.png)
> ![image](https://user-images.githubusercontent.com/1361563/96477748-3f408580-120d-11eb-8dad-269c0db7d6e1.png)
> ![image](https://user-images.githubusercontent.com/1361563/96477773-44053980-120d-11eb-9e3c-b56a42ac857a.png)
> ![image](https://user-images.githubusercontent.com/1361563/96477785-48c9ed80-120d-11eb-9b15-1aa7de4a841c.png)
> ![image](https://user-images.githubusercontent.com/1361563/96478096-a827fd80-120d-11eb-8415-ee64cf3e1bab.png)
> ![image](https://user-images.githubusercontent.com/1361563/96478188-c2fa7200-120d-11eb-8814-8986a3c16952.png)

Seems like you have optifine without having optiforge, it will fix most of the missing textures, as for the books, it's a patchouli bug which is fixed in the latest patchouli version which will be in the next pack release

**Comment by andrewsf** [comment] 2020-10-20 22:02
I can confirm that replacing `Patchouli-1.16.2-45.jar` with `Patchouli-1.16.2-47.jar` did resolve models for Woot, Industrial Foregoing, Nature's Aura, Cyclic, Immersive Engineering, and Mystical Agriculture. Those are the ones I already had on hand.

**Comment by Blntswrd** [comment] 2020-11-01 11:36
I can say that the textures for Silent Gear, at least the tip upgrades are caused by something in the modpack. They show textures when alone.

**Comment by ghostbear77** [comment] 2020-11-10 08:33
I noticed missing textures for SIlentGear materials in JEI, but figured that was a minor error that I could live with. When I upgraded my Pickaxe with the Shovel-Mod, the Icon in the inventory and the hand model were broken :(
I played around with the Resourcepack-menu and behold, after the reload the Pickaxe model was back :)
But now the Rune- and Xperience ores from Forbidden & Arcanus have some item as side-textures in world and produce an X-Ray view behind them. Item-versions obtained with Silktouch do look normal.

My solution for now is to move the "incompatible" PackMenu Resource one position up or down to force this reload. It only works after loading into my world, though, doing so in the main menu just crashed the game.

**Comment by Dextryan** [comment] 2020-12-31 20:18
You can do F3 + T to reload resource packs. It will bug others textures but less relevant ones, it is very efficient but you have to do it everytime you load your world

**Comment by Hannes1909** [comment] 2021-01-02 17:04
+1 for ghostbears problem. F3+T fixes the Silent Gear stuff, but seems to mess with Refined Storage and some other textures:
![image](https://user-images.githubusercontent.com/29476657/103462344-d99c6980-4d24-11eb-8b85-74a927f14b19.png)

Workaround for me is to live with the broken RS textures since the pickaxe and armor are visible more often ;-)

**Comment by whatthedrunk** [comment] 2021-01-06 02:50
Original issue is fixed with the silent gear and natures stuff. If you are having issues with other textures in 1.3.9b make a new issue thanks!

**Closed by whatthedrunk** 2021-01-06 02:50 UTC
Labels: Bug
