### ISSUE TITLE
Ghost over spawn

### ISSUE THREAD

**Issue by cc3768** [AllTheMods/ATM-6#1676] opened 2021-05-23 01:00 UTC
ATM 6 Version 1.6.4
Describe the bug
The nether spawns with over 1000 ghosts 

To Reproduce
Enter The Nether

Screenshots
![2021-05-22_20 54 56](https://user-images.githubusercontent.com/5598486/119244660-b5f58680-bb40-11eb-83f3-e5f9b0ea49fa.png)
![2021-05-22_20 54 59](https://user-images.githubusercontent.com/5598486/119244661-b5f58680-bb40-11eb-82ba-cff43448518c.png)
![2021-05-22_20 55 02](https://user-images.githubusercontent.com/5598486/119244662-b5f58680-bb40-11eb-9e3e-c6e09b40d045.png)

**Comment by thevortex** [comment] 2021-05-23 12:08
duplicate of #1656 , add config file from #1658 and reset the nether to resolve

**Closed by thevortex** 2021-05-23 12:08 UTC
