### ISSUE TITLE
Refined storage autocrafter not noticing resorces

### ISSUE THREAD

**Issue by RainTheHatellc** [AllTheMods/ATM-6#1968] opened 2021-07-09 20:43 UTC
ATM6 Version 1.6.10

Refined storage won't autocraft extra disk memory parts.

So I have a Refined Storage system set up with autocrafting, and I've put in all of the recipes to make the infinite storage part from Extra Disks. When I click to craft it, it tells me I'm missing 81 of the 16384k parts, no other information. When I tell it to make 81 of those parts, it tells me I'm missing 729 of the 1024k parts. It will let me order those, and I in fact just finished crafting 729 of the 1024k parts. So I now have 729 of these parts setting in storage, but it still tells me they are missing when I try to craft any storage part larger then 1024k. It won't even let me craft the 4096k part, because it says I am missing 3 1024k parts. Which I am OBVIOUSLY not, I have over 700 of the bastards. I have double and triple and quadruple checked to make sure I have all of the blueprints in there, and they are all there, what is going on?

**Comment by BovineShaman** [comment] 2021-07-09 20:52
Update the modpack to the most recent version, and then redo all of the relevant patterns. 
There were two mods that made functionally the same items, and was fixed in 1.6.11.

**Comment by RainTheHatellc** [comment] 2021-07-09 23:02
Well I don't control the server, so I'll mention something to the admins i guess.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BovineShaman** [comment] 2021-07-14 22:34
If/when your server is updated, re-do your patterns, and try crafting again.
If the issue is still present after updating, feel free to reopen this issue.

**Closed by BovineShaman** 2021-07-14 22:34 UTC
Labels: Bug
