### ISSUE TITLE
Jumping from singleplayer to multiplayer after leaving a SP world

### ISSUE THREAD

**Issue by Finnchen123** [AllTheMods/ATM-6#901] opened 2021-01-20 18:10 UTC
Version: 1.4.1 (current)

I don't rly know if this is a pack, forge or mc related issue but when I leave a singleplayer world it automatically jumps to multiplayer. During the "Exiting world and loading menu"-time I don't press or click anything.

I just wanted to ask if this is sth. pack related?

**Comment by jeremiahwinsley** [comment] 2021-01-20 18:12
Yes, known bug.  Duplicate of #730

**Closed by jeremiahwinsley** 2021-01-20 18:12 UTC
Labels: Question
