### ISSUE TITLE
[Bug]: Engineers hammer > ingots not making plates unless hammer full durability

### ISSUE THREAD

**Issue by filikun** [AllTheMods/ATM-6#2501] opened 2021-10-04 08:51 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.5

### What happened?

So Engineers hammer does not make plates if the hammer durability is not 100%.

![image](https://user-images.githubusercontent.com/9947929/135821459-c8bdae87-b9ee-4549-a905-7c3ea8e993a6.png)

![image](https://user-images.githubusercontent.com/9947929/135821067-3c27b94c-00f6-4fc0-b99a-64322916466e.png)

![image](https://user-images.githubusercontent.com/9947929/135821136-7784e3de-f916-4a7b-bc04-6ba784bbbd4b.png)

### latest.log

https://gist.github.com/filikun/5ee7660605c33ef59b770a1d4b85f380

**Comment by ladylexxie** [comment] 2021-10-04 11:57
Duplicate of #2456

**Closed by ladylexxie** 2021-10-04 11:57 UTC
Labels: Bug
