### ISSUE TITLE
Immersive Engineering Coal Coke

### ISSUE THREAD

**Issue by TheBossManGamer** [AllTheMods/ATM-6#1383] opened 2021-04-10 11:58 UTC
Pack Version: 6-1.5.10
**Describe the bug**
Coke Ovens no longer accept coal, or if you do put it in, it acts as a server desync issue where it will end up in your inventory again. This makes producing creosote oil impossible. Breaking the multi block and reforming it made no difference
**To Reproduce**
1. Make Coke Oven
2. Try to make coal coke
3. Fail to get it in the inventory successfully
4. See problem

**Screenshots**
This is applicable sort of but wont help illustrate the point better and I already closed MC so I apologize for not including them

**Additional context**
This was made prior to the latest update (6-1.5.10) and worked just fine before updating the pack. I noticed there was a few minor issues not necessary related to Immersive Engineering as well but do not actually know if any of that is related or just mod updates stacking on this release.

**Logs**
Admittedly I am not certain where I might log this behavior, would be happy to include logs if it might be applicable somewhere, but the console did not throw errors so I am not sure if there would be any relevant info there

**Comment by Zargachi** [comment] 2021-04-10 13:22
Improved Blast Furnace also have this bug, probably normal Blast Furnace too, the Alloy Kiln also have this bug but it just don't do the recipe, the items continues inside.

**Comment by ScreamingSpleen** [comment] 2021-04-10 14:01
Arc Furnace, Crusher, Industrial Squeezer, Metal Press all also have this issue described above. This is since the 1.5.10 version. Even rebuilding the machines does not solve the issue. Seems Immersive Engineering is unusable  at this time.

**Comment by TheBossManGamer** [comment] 2021-04-11 06:10
6-1.5.10b did not fix this issue

**Comment by Zargachi** [comment] 2021-04-13 04:08
today i was playing in my server with a friend and i don't know why but the coke oven, improved blast furnace and alloy kiln started to work again for no reason, then i needed to restart my server and when it opened these constructions stopped working again, for me or my friend, the problem is the same, for some reason the fluid in-out of coke oven works normal, and fuel of alloy kiln too, it's just the process that doesn't work.

**Comment by Leithas** [comment] 2021-04-13 19:17
Confirmed still an issue:  Playing on a hosted private server; no resource packs ~ "vanilla" All the mods 6.  10b.  

Assembled the coke oven as usual; animation shows correctly on assemble.  GUI works (seemingly) but processes won't kick off/start.  Product seems to feed nicely into the left side as usual but process doesn't start.  No 'burning' animation on exit (the coke oven remains dark).  Exit GUI ok but the product ends up spitting back to player inventory when you try to re-engage the GUI (which is then empty).

Tried assembling in different order (top/bottom etc..), different locations and with chunk loaded/not loaded etc...

**Comment by whatthedrunk** [comment] 2021-04-15 22:57
This should all be fixed in 1.6.0 that is out now. If not please let me know what OS your server is on.

**Closed by whatthedrunk** 2021-04-15 22:57 UTC
Labels: Bug
