### ISSUE TITLE
Advanced Crafting Stick Crash

### ISSUE THREAD

**Issue by Dextryan** [AllTheMods/ATM-6#695] opened 2020-12-30 03:58 UTC
Advanced crafting stick makes game crash when using "Empty the grid" button

1. Open The Advanced Crafting Stick
2. Click on "Empty the grid"
3. Boom the game crashed!

**Comment by Xechorizo** [comment] 2020-12-30 12:14
Dupe of [#685](https://github.com/AllTheMods/ATM-6/issues/685)?

**Comment by Dextryan** [comment] 2020-12-31 13:55
I dont believe so, I had room in my inventory and wasnt playing in a server.

**Comment by Perryman** [comment] 2020-12-31 21:12
Looks like Lothrazar fixed this in 1.0.2 of Cyclic, suggest the modpack team updates.  See below for full details.

[update.json](https://github.com/Lothrazar/Cyclic/blob/08ddde01667fb64d9b31bbff3ce7041705d07090/update.json)

[Cyclic #1656](https://github.com/Lothrazar/Cyclic/issues/1656)
[Cyclic #1652](https://github.com/Lothrazar/Cyclic/issues/1652)
[Cyclic #1637](https://github.com/Lothrazar/Cyclic/issues/1637)

I have closed #685 to make this primary as it is more broad in scope and has other consequences within Cyclic per the above threads.  I have not tested ATM 6 with Cyclic 1.0.2.

**Closed** 2021-01-04 15:29 UTC
Labels: Bug
