### ISSUE TITLE
Ghosts

### ISSUE THREAD

**Issue by KILLERmanJAYR0** [AllTheMods/ATM-6#1693] opened 2021-05-24 20:25 UTC
Are the ghost supose to spawn in the hundreds in the nether with 1500 health and the capability of one shoting you?
Im in The Other: Soul Sand Vally

All the Mods 6-1.6.4

![unknown](https://user-images.githubusercontent.com/84743198/119403582-7e204780-bcd6-11eb-9997-faf521c39d4d.png)

**Comment by thevortex** [comment] 2021-05-24 20:39
duplicate of #1656 use the file in #1658 for resolution, reset the nether dimension

**Closed by thevortex** 2021-05-24 20:39 UTC
Labels: Question
