### ISSUE TITLE
Minecraft crashing after open world, Update from 1.6.14 to 1.8.3

### ISSUE THREAD

**Issue by GabrielDZN** [AllTheMods/ATM-6#2412] opened 2021-09-20 15:44 UTC
Minecraft crashing after open world
Version 1.8.3

1. Open Minecraft
2. Open The World
3. wait
4. crash

Additional contex
I've updated modpack from version 1.6.14 to version 1.8.3 and I can't open my map, +50hours, I don't want to lose what I already have on it, I have security backups, I just wanted to play in the new version with draconic

Logs
https://pastebin.com/qhY97ATW
https://pastebin.com/qhY97ATW
https://pastebin.com/qhY97ATW

**Comment by GabrielDZN** [comment] 2021-09-20 16:03
without optifine same bug

**Comment by SlackerNet** [comment] 2021-09-20 16:10
version 1.7 had a required world reset, version 1.8 had a recommended world reset....you would be better off trying to add draco to the mods list and see what happens.....otherwise you need start a new world as the updates recommended

**Comment by GabrielDZN** [comment] 2021-09-20 16:12
> version 1.7 had a required world reset, version 1.8 had a recommended world reset....you would be better off trying to add draco to the mods list and see what happens.....otherwise you need start a new world as the updates recommended

wouldn't there be a way to save some chunks, so as not to lose buildings and things like that?, if so how do I do it safe, like a way to reset chunks, and save others?

**Comment by SlackerNet** [comment] 2021-09-20 16:24
the problem is corruption.....as mods are added and removed so are info assigned to it. So yes you can add the world edit mod....copy and save a building schematic. The problem is if there are special non vanilla blocks you could be placing a building with blocks that don't exist..... so to answer the question...can it be done ?---yes world edit can do that....will it work..... no promises

**Comment by ladylexxie** [comment] 2021-09-22 20:50
The crash is related to an item you have in your inventory, you can manually edit it by using an NBT editor and removing any item that is part of the removed mods.

**Closed by ladylexxie** 2021-09-22 20:50 UTC
Labels: Bug
