### ISSUE TITLE
Minecolonies don't work (after the update?)

### ISSUE THREAD

**Issue by lngry** [AllTheMods/ATM-6#396] opened 2020-11-25 15:31 UTC
So i'm playing with my friends atm6 and they've made their (1) colony that they share together, and few days before i made my own too,  and i did build there  building hut, one house (for the builder) and tavern. 

 but after the new updates when i tried to make another buildings (townhall, restaurant, another house, second builders hut..) the server says: you are not allowed to place colonies in other dimensions (this is changeable in config files) 

Also it let's me to build decoration categorys  "buildings" but not anything else. And with my friends they can build new buildings, but only with the building tool? One of my friends said that without the building tool he gets the same message "you are not allowed to place colonies in other dimensions.."

(Also server owner have tried to change config files few times but nothing works) 

Anyone else have this same problem? This is very frustrating because i really like this modpack and i've really  liked building my own colony. Any tips what we should do?

**Comment by lngry** [comment] 2020-11-26 23:25
Help:(

**Comment by ViRb3** [comment] 2020-11-27 13:04
https://github.com/ldtteam/minecolonies/issues/6146

**Comment by Raycoms** [comment] 2020-11-27 14:53
"ok, it looks like this was a temporary bug, latest version new server file on 1.3.3 did work. It looks like there was a forge build that messed up the dimensions, don't know which one though."

**Comment by ViRb3** [comment] 2020-11-27 14:55
We are testing this theory right now, will report back :)

**Comment by ViRb3** [comment] 2020-11-27 17:40
Indeed, the problem was Forge's incorrect dimension handling before https://github.com/MinecraftForge/MinecraftForge/pull/7513 was merged. To work around this issue, as well as every other dimension issue caused by Forge over the past weeks, I propose the following "universal" solution:

1. Update to ATM6 1.3.3, which has the fixed Forge version 35.1.4.
1. Rename the `world` folder with all of your world data. __BACK IT UP ADDITIONALLY, JUST IN CASE__
2. Use NBTEdit to get the seed for the existing world.
3. Edit your `server.properties` and set the `seed=` to your old seed noted above.
4. Start the server. A new, fresh, bug-free world will be generated.
5. Stop the server.
6. Copy over the `level.dat` from the __new__ world to the old world. 
- If your end dimension is impacted by the dimension bug, delete your `DIM1` folder.
- If your nether dimension is impacted by the random biome bug, delete your `DIM-1` folder.
- If you can, delete any additional dimension folders, such as the whole `dimensions` folder. Of course, make sure you don't have anything important in those dimensions.
7. Delete/rename the __new__ world folder.
8. Rename back the __old__ world folder to what it was originally.
9. Restart the server. Everything should be fixed.

We tested this on our server and it worked great. Hope it helps people.

**Comment by NetMasterFlex** [comment] 2020-11-27 20:40
Does this fix apply if I’ve already updated to ATM 1.3.3?  Or should the issue be fixed already?

**Comment by ViRb3** [comment] 2020-11-27 20:42
Yes, the fix applies if you have updated to ATM 1.3.3+. No, the issue will not be able to fix itself, ever. It will only stop happening on newly created worlds.

**Comment by NetMasterFlex** [comment] 2020-11-27 20:50
Thanks. I have an existing world map that has hours of progress in it. Just applied for safe measure in case I decide to use the affected mod issue.

**Closed** 2020-11-28 12:49 UTC
Labels: Bug, Mod Issue, Reported
