### ISSUE TITLE
All the Mods 6-1.1.0 server crash

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [AllTheMods/ATM-6#152] opened 2020-10-08 20:59 UTC
**Describe the bug**
Server crashed, no idea what caused it.

**To Reproduce**
No clue, will update if it happens again and I figure it out.

**Expected behavior**
Server not to crash.

**Additional context**
Player was crafting when the crash happend, not sure if this is related.

**Crash log**
https://pastebin.com/tEtRmJ5L

**Update:**
The server does crash from time to time. Here are the crashlogs:

Note; Running on 4 dedicated cores from a Ryzen 2700X and 8Gb ram soley for the MC server. Other then the random crashes TPS is usually 20.

- https://pastebin.com/8nQXkRGU
- https://pastebin.com/KvUqzaHJ
- https://pastebin.com/wG3jAinm

There are more if necessary.

**Comment by WhitePhant0m** [comment] 2020-10-09 00:04
Seems to be caused by vines growing on a specific block, for now you could do `/gamerule randomTickSpeed 0` to disable vines growing(or anything that uses the same function) so it doesn't cause the crash.

**Comment by Sirttas** [comment] 2020-10-09 09:01
fixed in elementalcraft: https://github.com/Sirttas/ElementalCraft/issues/4

**Comment by MathiasDeWeerdt** [comment] 2020-10-09 18:58
> fixed in elementalcraft: [Sirttas/ElementalCraft#4](https://github.com/Sirttas/ElementalCraft/issues/4)

Awesome!

**Comment by MathiasDeWeerdt** [comment] 2020-10-09 19:12
Added an update with more crashes with another cause.

**Closed** 2020-10-10 15:05 UTC
Labels: Crash
