### ISSUE TITLE
 minor sneaking bug

### ISSUE THREAD

**Issue by LoneWolf137** [AllTheMods/ATM-6#1955] opened 2021-07-06 09:55 UTC
1.6.14
this is an odd one. in all worlds i created before this update, i am semi stuck in sneak. i can sprint (if slower) and still fall of blocks, but my camera is lowered and i "autosneak" when going under half slaps. i can still sneak, but it doesnt fix it. it does not happen in new worlds, and the "autosneak" doesnt happen there as well.

i have no clue what caused it tbh, and it isnt much of a priority i would say.

https://user-images.githubusercontent.com/42692808/124580084-0f471a00-de50-11eb-845c-941243cb6dc7.mp4

**Comment by radiomike** [comment] 2021-07-06 11:50
Duplicate of #1901

**Closed** 2021-07-09 02:07 UTC
Labels: Bug
