### ISSUE TITLE
All Mystical Agriculture seeds can no longer be used with Botania Pots

### ISSUE THREAD

**Issue by TheBigunF20** [AllTheMods/ATM-6#1888] opened 2021-06-24 06:50 UTC
Pack Version: 1.6.10

The recipe and interaction between Mystical Agriculture seeds and Botania Pots/Hopper Pots is gone. Presumably something to do with the most recent updates comment:

• Added missing Mystical Agriculture seeds to Botania Pots and Garden Cloches

Although Garden Cloches appear to be unaffected.

Recipe
1. Use JEI to search for any Mystical Agriculture seed
2. Check Recipes using any MA seed
3. See that there is no interaction between any MA seed and Botania Pot/Hopper Pot 
NOTE: Alternatively you can search through the Botania Pot recipes and find no MA seeds, though this is a much longer process.

Interaction:
1. Place down Botania Pot/Hopper Pot
2. Insert any type of soil into Pot
3. Attempt/Fail to place any type of MA seed on the soil in the pot

**Additional context**
This includes both Pots which were already placed and had MA seeds in them (which have simply disappeared), as well as newly placed pots, soils, and MA seeds.

**Logs**

https://pastebin.com/PzgXnSPP

**Comment by DAmNRelentless** [comment] 2021-06-24 07:52
![](https://i.imgur.com/7ElyCDn.png)
![](https://i.imgur.com/zg9iidA.png)

Works as intended.
There was an issue in 1.6.9 where this wasn't possible but it was fixed in 1.6.10. That's also why it's written in the changelog.
Either you are not playing the most up to date version or your launcher didn't properly overwrite the files but it definitely works.

**Closed by DAmNRelentless** 2021-06-24 07:52 UTC
Labels: KubeJS
