### ISSUE TITLE
Displacement Enchantment and Endermites

### ISSUE THREAD

**Issue by waybaker** [AllTheMods/ATM-6#631] opened 2020-12-21 19:03 UTC
**Describe the bug**
When using the Enchantment "Displacement", if you are attacked by an endermite, the game will hard crash the server.

**To Reproduce**
1. Setup an All The Mods 6 server (I am running in Linux on 1.3.5)
2. Enchant a piece of Armor with Displacement (Currently have mine at Displacement IV on a Steel Jetpack from the Iron Jetpacks Mod and Displacement V on a pair of AllTheModium Boots)
3. Enter the End and find an endermite (easily found in the End Mines, plenty of spawners)
4. Endermite enters your hitbox and the server crashes, closing the connection to the client.

**Expected behavior**
The endermite should be teleported away and server should not crash.

**Screenshots**
Screenshots showing other enchantments on Jetpack and Boots for Displacement Enchantment and Helmet and Leggings just in case.
![Boots](https://user-images.githubusercontent.com/25492475/102812270-c092d080-4394-11eb-9807-b56fe29cbf0c.png)
![Jetpack](https://user-images.githubusercontent.com/25492475/102812279-c2f52a80-4394-11eb-8dad-51be68b9602a.png)
![Helmet](https://user-images.githubusercontent.com/25492475/102812499-1a939600-4395-11eb-83e3-202fe7d0aad6.png)
![Leggings](https://user-images.githubusercontent.com/25492475/102812506-1cf5f000-4395-11eb-9937-05134cf650ca.png)

**Additional context**
From last nights Crash Log:

```
[20Dec2020 22:29:14.870] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 138ab89a-163a-4fdf-99b9-099c59a13d45
[20Dec2020 22:29:14.876] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_272]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) ~[?:1.8.0_272]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_272]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_272]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_272]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_272]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_272]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_272]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_272]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_272]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?]
	at net.minecraft.entity.monster.EndermiteEntity.func_70636_d(SourceFile:134) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.entity.monster.EndermiteEntity.func_70071_h_(SourceFile:110) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	... 5 more
```

**Comment by ViRb3** [comment] 2020-12-22 00:11
Dupe of #374

**Closed by ViRb3** 2020-12-22 00:11 UTC
Labels: Bug
