### ISSUE TITLE
ATM 6 1.8.2 is not working

### ISSUE THREAD

**Issue by Centrical49** [AllTheMods/ATM-6#2353] opened 2021-09-13 18:32 UTC
Failed to start the minecraft server
java.lang.RuntimeException: No key seed in MapLike[{"type":"mythicbotany:alfheim_generator","biome_source":{"type":"mythicbotany:alfheim_biomes"}}]; No key seed in MapLike[{"type":"mythicbotany:alfheim_biomes"}]
        at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[?:?] {re:classloading}
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[?:?] {re:classloading}
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[?:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:153) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.4.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.4.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.4.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.4.jar:?] {}
It worked on 1.8.1 but it said that was FML incompatible server

**Comment by Rice-SD** [comment] 2021-09-13 19:11
This a duplicate to https://github.com/AllTheMods/ATM-6/issues/2352

**Comment by tabdelbari** [comment] 2021-09-13 19:33
i have the same problem on Ubuntu 18.04, just installed the server and this is the result:
[13Sep2021 18:54:49.043] [Worker-Main-3/INFO] [immersiveengineering/]: Finished recipe profiler for Arc Recycling, took 2560 milliseconds
[13Sep2021 18:54:49.044] [Worker-Main-3/INFO] [minecolonies/]: Beginning load of custom recipes for colony workers
[13Sep2021 18:54:49.237] [Worker-Main-3/INFO] [minecolonies/]: Loaded 464 recipes for 13 crafters
[13Sep2021 18:54:49.253] [Worker-Main-3/INFO] [minecolonies/]: Finished discovering compostables 2382
[13Sep2021 18:54:49.254] [Worker-Main-3/INFO] [minecolonies/]: Beginning load of research for University.
[13Sep2021 18:54:49.323] [Worker-Main-3/INFO] [minecolonies/]: Loaded 183 recipes for 4 research branches
[13Sep2021 18:54:49.764] [Worker-Main-3/INFO] [com.stal111.forbidden_arcanus.gui.forbiddenmicon.ForbiddenmiconPageLoadListener/]: Loaded 18 recipes
[13Sep2021 18:54:49.783] [Worker-Main-3/INFO] [Apotheosis : Enchantment/]: Registered 11 blocks with enchanting stats.
[13Sep2021 18:54:49.787] [Worker-Main-3/INFO] [Apotheosis : Deadly/]: Loaded 13 normal and 13 rare Wandering Trader trade options.
[13Sep2021 18:54:49.790] [Worker-Main-3/INFO] [Cucumber Library/]: Loaded cucumber-tags.json in 1 ms
[13Sep2021 18:54:49.819] [Worker-Main-3/INFO] [slimeknights.tconstruct.library.materials.definition.MaterialManager/]: 36 materials loaded
[13Sep2021 18:54:50.404] [Worker-Main-3/INFO] [slimeknights.tconstruct.library.materials.stats.MaterialStatsManager/]: 108 stats loaded for 36 materials
[13Sep2021 18:54:51.471] [Worker-Main-3/INFO] [immersiveengineering/]: Recipes for potions: upgrade_aquatic:restfulness_strong, minecraft:strong_slowness, minecraft:slowness, minecraft:night_vision, quark:long_danger_sight, minecraft:strong_regeneration, apotheosis:fatigue, apotheosis:long_knowledge, quark:long_resistance, ars_nouveau:spell_damage_strong, apotheosis:strong_fatigue, minecraft:strong_swiftness, minecraft:long_slowness, potionsmaster:unobtainium_sight, upgrade_aquatic:repellence, cyclic:swimspeed, potionsmaster:vibranium_sight, minecraft:mundane, minecraft:weakness, mana-and-artifice:greater_mana_potion, ars_nouveau:spell_damage, minecraft:long_regeneration, potionsmaster:lapis_sight, apotheosis:strong_haste, minecraft:long_leaping, apotheosis:long_haste, minecraft:long_fire_resistance, quark:strong_resistance, upgrade_aquatic:repellence_strong, potionsmaster:aluminium_sight, potionsmaster:gold_sight, cyclic:stun, minecraft:long_turtle_master, eidolon:long_anchored, minecraft:long_water_breathing, potionsmaster:platinum_sight, potionsmaster:osmium_sight, apotheosis:long_wither, ars_nouveau:mana_regen_potion_strong, upgrade_aquatic:vibing, apotheosis:haste, minecraft:swiftness, potionsmaster:quartz_sight, apotheosis:long_fatigue, apotheosis:strong_wither, potionsmaster:diamond_sight, minecraft:strong_healing, apotheosis:wither, minecraft:thick, minecraft:strong_strength, minecraft:invisibility, potionsmaster:crimsoniron_sight, apotheosis:resistance, potionsmaster:allthemodium_sight, potionsmaster:uranium_sight, minecraft:luck, minecraft:slow_falling, minecraft:strength, apotheosis:absorption, quark:resistance, minecraft:long_night_vision, minecraft:long_slow_falling, upgrade_aquatic:repellence_long, potionsmaster:zinc_sight, ars_nouveau:mana_regen_potion_long, potionsmaster:nickel_sight, minecraft:awkward, potionsmaster:redstone_sight, mana-and-artifice:superior_mana_potion, minecraft:turtle_master, apotheosis:long_absorption, upgrade_aquatic:vibing_long, cyclic:strong_haste, potionsmaster:lead_sight, minecraft:fire_resistance, minecraft:harming, minecraft:long_weakness, potionsmaster:netherite_sight, apotheosis:knowledge, minecraft:long_poison, potionsmaster:bismuth_sight, eidolon:chilled, potionsmaster:iron_sight, apotheosis:strong_resistance, upgrade_aquatic:insomnia, upgrade_aquatic:insomnia_strong, minecraft:leaping, minecraft:strong_turtle_master, ars_nouveau:mana_regen_potion, mana-and-artifice:light_mana_potion, apotheosis:strong_absorption, potionsmaster:copper_sight, quark:long_resilience, minecraft:water, quark:strong_resilience, minecraft:water_breathing, quark:danger_sight, apotheosis:sundering, eidolon:long_chilled, upgrade_aquatic:restfulness, quark:resilience, minecraft:strong_poison, apotheosis:long_resistance, minecraft:healing, minecraft:long_strength, upgrade_aquatic:vibing_strong, apotheosis:long_sundering, cyclic:haste, eidolon:anchored, potionsmaster:coal_sight, mana-and-artifice:minor_mana_potion, apotheosis:strong_sundering, minecraft:strong_harming, minecraft:strong_leaping, minecraft:long_swiftness, minecraft:poison, minecraft:regeneration, apotheosis:strong_knowledge, potionsmaster:silver_sight, minecraft:long_invisibility, potionsmaster:emerald_sight, mana-and-artifice:mana_potion, potionsmaster:tin_sight, ars_nouveau:spell_damage_long
[13Sep2021 18:55:51.396] [main/INFO] [minecolonies/]: Tags Loaded
[13Sep2021 18:55:51.446] [main/INFO] [TerraForged/]: Tags Reloaded
[13Sep2021 18:55:53.093] [main/INFO] [net.roguelogix.biggerreactors.BiggerReactors/]: Loading reactor moderators
[13Sep2021 18:55:53.391] [main/INFO] [net.roguelogix.biggerreactors.BiggerReactors/]: Loaded 52 moderator data entries
[13Sep2021 18:55:53.396] [main/INFO] [net.roguelogix.biggerreactors.BiggerReactors/]: Loaded 77 moderator entries
[13Sep2021 18:55:53.404] [main/INFO] [net.roguelogix.biggerreactors.BiggerReactors/]: Loading turbine coils
[13Sep2021 18:55:53.692] [main/INFO] [net.roguelogix.biggerreactors.BiggerReactors/]: Loaded 15 coil data entries
[13Sep2021 18:55:53.697] [main/INFO] [net.roguelogix.biggerreactors.BiggerReactors/]: Loaded 30 coil entries
[13Sep2021 18:55:53.706] [main/INFO] [net.roguelogix.biggerreactors.BiggerReactors/]: Loading fluid transitions
[13Sep2021 18:55:53.998] [main/INFO] [net.roguelogix.biggerreactors.BiggerReactors/]: Loaded 6 transitions data entries
[13Sep2021 18:55:54.003] [main/INFO] [net.roguelogix.biggerreactors.BiggerReactors/]: Loaded 6 liquid transition entries
[13Sep2021 18:55:54.003] [main/INFO] [net.roguelogix.biggerreactors.BiggerReactors/]: Loaded 7 gas transition entries
[13Sep2021 18:55:54.008] [main/INFO] [TerraForged/]: Tags Reloaded
[13Sep2021 18:56:00.332] [main/INFO] [TerraForged/]: Loading vanilla base decorator
[13Sep2021 18:56:00.717] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
java.lang.RuntimeException: No key seed in MapLike[{"type":"mythicbotany:alfheim_generator","biome_source":{"type":"mythicbotany:alfheim_biomes"}}]; No key seed in MapLike[{"type":"mythicbotany:alfheim_biomes"}]
        at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[?:?]
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[?:?]
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:153) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.4.jar:36.2]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.4.jar:?]
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.4.jar:?]
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.4.jar:?]

**Comment by ladylexxie** [comment] 2021-09-14 04:44
Duplicate of #2348

**Closed by ladylexxie** 2021-09-14 04:44 UTC
Labels: Bug
