### ISSUE TITLE
Server crash from (pressumably) rats mining something

### ISSUE THREAD

**Issue by dannypas00** [AllTheMods/ATM-6#657] opened 2020-12-23 18:25 UTC
**Describe the bug**
The ATM6-1.3.7 server crashes on-load (after crashing once during runtime) because of a mining rat.

**To Reproduce**
Unknown how to reproduce from scratch, however this is what happened to us:
1. User is mining using rats' mining rats
2. Rat mines a certain unknown block
3. Server crashes; throws a ``java.lang.IllegalArgumentException`` exception
4. Server restarts
5. Server crashes after finishing loading (pressumably once the chunks load)

**Expected behavior**
The server does not crash, the rat should mine the block as normal

**Additional context**
The only suspects around the location of the rat as stated in the logs are tin ore, lead ore, flowing water, and a dirt block with a poppy on it.

**Logs**
The crash log:
[crash-2020-12-23_18.40.52-server.txt](https://github.com/AllTheMods/ATM-6/files/5736583/crash-2020-12-23_18.40.52-server.txt)

**Comment by ViRb3** [comment] 2020-12-23 21:33
Dupe of #539

**Closed by ViRb3** 2020-12-23 21:33 UTC
Labels: Bug
