### ISSUE TITLE
Hives don't shear well

### ISSUE THREAD

**Issue by DeathOfTime** [AllTheMods/ATM-6#251] opened 2020-11-01 02:11 UTC
**Describe the bug**
I had a dispenser use a pair of shears on a tier two hive. After the hive got full it would shear it. Three vanilla combs would come out and the hive would appear empty visually. when inspected by the one probe it would show as having eight combs in it. Every time a bee deposited a comb it would visually show up as full and get sheared again. Every time it would produce three combs but no actual combs were taken from the hives inventory.

**To Reproduce**
1. Place Down a Hive
2. Have a dispenser use shears on it instead of a scraper
3. Watch as the combs pile up in the hive

**Expected behavior**
From the sounds of "fifty shades of bee" all the combs in the hive should drop when it is sheared. One comb at a time should drop when it is scraped. The hive must be completely emptied before it will get more combs.

**Screenshots**
![2020-10-31_21 02 30](https://user-images.githubusercontent.com/15230368/97793687-555f2600-1bbd-11eb-8fed-2accc331f3b4.png)
![2020-10-31_20 50 50](https://user-images.githubusercontent.com/15230368/97793688-55f7bc80-1bbd-11eb-9010-bb111a785640.png)

**Additional context**
One screen shot is where i was using multiple bees for the same hive. The other screen shot was testing the same hive with just zombees

**Comment by WhitePhant0m** [comment] 2020-11-01 03:30
Shears are disabled, use a scraper.

**Comment by DeathOfTime** [comment] 2020-11-01 03:40
they aren't disabled very well then. they still work. they just don't at the same time

**Comment by DeathOfTime** [comment] 2020-11-01 03:41
you get three vanilla honey combs every time. no matter what combs are in the hive and the combs in the hive just keep piling up

**Comment by WhitePhant0m** [comment] 2020-11-01 04:18
Alright, I've informed the dev of the mod about this. I'll re-open this for now, will close when the update that fixes it is in the pack.

**Comment by Epic428** [comment] 2020-11-01 04:28
The issue is bc I changed how the dispenser behaviors were registered to prevent conflicts with other mods and ensure they got registered properly. As such even though we don't register the behavior when shears are disabled, the vanilla logic gets called as a fall back which causes the vanilla combs to appear bc of how the logic is coded. The only viable solution I can see is to override the behavior completely through mixin to add checks for our hive. In the meantime enjoy the free vanilla combs.

**Comment by Epic428** [comment] 2020-11-01 06:21
this has been fixed in dev. realized I didn't even need to use mixins

**Closed** 2020-11-24 18:29 UTC
Labels: Bug
