### ISSUE TITLE
[1.3.0] Crash when using elemental craft

### ISSUE THREAD

**Issue by lagonnebula** [AllTheMods/ATM-6#321] opened 2020-11-15 14:06 UTC
**Describe the bug**
I've put a crystal from elemental craft inside an infuser and the server crashed. I was unable to restart it without rollbacking the world. 
It seem that he try to load some particle server side ? 

**Additional context**
The world was generate with the version 1.2.1 of the modpack and updated to 1.3.0
Crash Log : https://pastebin.com/dk4gYhzU

**Comment by Sirttas** [comment] 2020-11-15 15:32
duplicate of https://github.com/AllTheMods/ATM-6/issues/308

**Comment by lagonnebula** [comment] 2020-11-15 15:36
Oh thanks, didn't saw it

**Closed** 2020-11-15 16:16 UTC
Labels: Bug
