### ISSUE TITLE
How to stop Ghosts from ice and fire from spawning. 

### ISSUE THREAD

**Issue by MrSparako** [AllTheMods/ATM-6#1663] opened 2021-05-21 16:39 UTC
All the Mods 6-1.6.4
I have an issue where there are about 500 ghosts around the player in my server, and I can't figure out how to disable them from spawning. My current fix right now is to make their HP to 1, and their attack power to .1, but this doesn't help with having 500 of them at a time.
![image](https://user-images.githubusercontent.com/62799958/119170527-5a88a300-ba31-11eb-9be8-f30889de006a.png)

**Comment by thevortex** [comment] 2021-05-21 21:41
duplicate of #1656 being addressed by #1658 please read over that, the resolutions presently the easier path forwards is take the file from the commit #1658 and add it to your server and reset the nether, you have biome corruption these mobs are not meant to spawn in the nether at all

**Closed by thevortex** 2021-05-21 21:41 UTC
Labels: Question
