### ISSUE TITLE
[1.3.3] ATM 6 delay and lag issue

### ISSUE THREAD

**Issue by 5bzkrmez** [AllTheMods/ATM-6#515] opened 2020-12-07 10:02 UTC
**Describe the bug**
while playing single-player locally after running the game for proximately 10 -20 mins without any issues a dealy happens of 1-2 sec on every command. The one prob shows a "waiting for server" message when looking to a new block.

**Screenshots**
illustrative video of the delay 

https://www.youtube.com/watch?v=N9DL1o03pBA&feature=youtu.be&ab_channel=%D8%B0%D9%8A%D8%A7%D8%A8Theyab

the logs of the video 
[latest.log](https://github.com/AllTheMods/ATM-6/files/5651819/latest.log)

a screenshot with F3 on  

![F3](https://user-images.githubusercontent.com/75610283/101336232-44c06080-388b-11eb-8988-39e935a6b0a5.png)

the dealy doesn't occur only in the nether. It randomly happens throughout the game and closing and opening the game removes it but it keeps coming back

I allocated 7008 MB ram for the game 
a java version of 8.0.2710.9
using cures forge laucher 0.0.76

**Comment by oly2o6** [comment] 2020-12-07 11:38
near duplicate of #505

**Closed** 2020-12-07 11:38 UTC
Labels: Bug, Duplicate
