### ISSUE TITLE
All The Mods 6 to the sky single player world crashes after reading world data. Version 1.8

### ISSUE THREAD

**Issue by gaypenguinz** [AllTheMods/ATM-6#2330] opened 2021-09-12 03:29 UTC
The bug I am experiencing is as the title states, whenever I load into my single player world it crashes after Reading World Data.

**To Reproduce**
I am not aware of how this problem occurred, but what happens includes:
1. I load into my single player world
2. The game loads past Reading World Data
3. The game then goes blank and crashes.

**Additional context**
I have tried waiting, about 45 minutes (just in case) with no luck.

**Logs**
https://pastebin.com/p1C2LPu2

**Comment by ladylexxie** [comment] 2021-09-12 12:53
This is an issue where your world didn't generate the correct config files, this is usually the cause of file corruption due to a power outage or some sort of incorrect way of closing the game.
I recommend making a new world and copying over the `/saves/world/serverconfig/` contents.

**Closed by ladylexxie** 2021-09-12 12:53 UTC
Labels: Bug
