### ISSUE TITLE
[Bug]:  Using Mine Colonies crashes client

### ISSUE THREAD

**Issue by officiallymarky** [AllTheMods/ATM-6#2867] opened 2022-01-06 16:25 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.16

### What happened?

Placing Supply Wagon crashes client.

I am not uploading a log as this is a known issue with a known solution.
https://github.com/ldtteam/minecolonies/issues/7885

"This is caused by tasgon/observable#23 and can be fixed by updating Observable."

### latest.log

https://gist.github.com/officiallymarky/ad1707d614ae717353627851ca1e791b

**Comment by radiomike** [comment] 2022-01-06 17:53
Duplicate of #2847

**Closed by radiomike** 2022-01-06 17:53 UTC
Labels: Bug
