### ISSUE TITLE
Mystical Agriculture mob seeds

### ISSUE THREAD

**Issue by Ghost-Asood** [AllTheMods/ATM-6#2377] opened 2021-09-16 13:46 UTC
Mystical Agriculture mob seeds (that needs a soul jar) recipes are corrupted. (ATM 6 1.8.2)

all the recipes have an empty soul jar, which means that each seed tier (1-6) only have 1 working recipe, for example if you placed 4 empty soul jars and imperium essence (thats a tier 4 seed) you will get a blaze seed, and even if you filled the jars with enderman souls for example, it'll still give you a blaze seed, and the same applies to all tiers.

**Comment by radiomike** [comment] 2021-09-16 14:03
Duplicate of #2350 and #2365

**Closed by radiomike** 2021-09-16 14:03 UTC
Labels: Bug
