### ISSUE TITLE
[1.5.2] Emerald and diamond duping with Mekanism and ElementalCraft or Astral Sorcery

### ISSUE THREAD

**Issue by nddragoon** [AllTheMods/ATM-6#1094] opened 2021-02-19 05:05 UTC
One emerald ore can be turned to 4 emeralds with an ore purifier and enrichment chamber or into 5 with starlight infusion, but only requires 3 emeralds to make in a combiner
![image](https://user-images.githubusercontent.com/54559451/108460186-c34b5e00-723d-11eb-9977-423b325cac15.png)
![image](https://user-images.githubusercontent.com/54559451/108460195-c6dee500-723d-11eb-8df0-65fc7dfa3917.png)
![image](https://user-images.githubusercontent.com/54559451/108460201-c9413f00-723d-11eb-9542-2da862377082.png)
![image](https://user-images.githubusercontent.com/54559451/108460207-ccd4c600-723d-11eb-9249-d29a4451174e.png)

**Comment by nddragoon** [comment] 2021-02-19 05:08
Also happens with diamonds

**Comment by Sirttas** [comment] 2021-02-19 07:18
Fixed in elemental craft 2.5.11

**Comment by nddragoon** [comment] 2021-02-19 12:57
Did you make pure emeralds and diamonds not enrichable? really i was hoping they'd just increase the amount needed to make an ore

**Comment by TBoshoven** [comment] 2021-02-19 14:38
This is a duplicate of #856 .
As mentioned there, this is also possible for Nether Quartz and Fluorite.

I'm with @nddragoon though. This is more of a Mekanism thing than an Elementalcraft thing.
It is possible to do much better in terms of diamond yield using AstralSorcery, or even just a diamond pick with a high level of fortune on it (can easily be fully automated using modular routers).

In general, I think the combiner is probably just not a good idea.

**Comment by Sirttas** [comment] 2021-02-20 15:29
> Did you make pure emeralds and diamonds not enrichable? really i was hoping they'd just increase the amount needed to make an ore

I cannot change mekanism recipes

**Comment by Sirttas** [comment] 2021-02-20 15:33
> In general, I think the combiner is probably just not a good idea.

I agree, but the compatibility is an elemental craft feature that I added after mekanism introduced their combiner. So I make sure that my feature doesn't break anything. 

Finally, I made it fully configurable so if someone wat to make the changes I am willing to walk them through the config.

**Comment by TBoshoven** [comment] 2021-02-20 17:16
Yup I think the decision was the right one from your end @Sirttas but I think this should be resolved on Mekanism's end (maybe for 1.17?).

Looking at previous reports (https://github.com/mekanism/Mekanism/issues/5102 https://github.com/mekanism/Mekanism/issues/5107 https://github.com/mekanism/Mekanism/issues/5636) they seem to be uninterested in making changes to the Combiner to accommodate even very popular mods (Thermal Expansion in this case).

I'll probably open an issue there so they're aware of it (not so much the ElementalCraft thing, but the other ones as well) but I think it'll be on the ATM6 team to tweak recipes in this case.

**Closed** 2021-04-15 23:05 UTC
Labels: KubeJS
