### ISSUE TITLE
Armor duplication

### ISSUE THREAD

**Issue by Mickdestroy87** [AllTheMods/ATM-6#694] opened 2020-12-30 01:01 UTC
It's possible to duplicate armor (maybe something else, I didn't really search more)

To reproduce
1. You can put an armor on you but it need to be different than the armor you want to duplicate (or don't put any armor at all)
2. Open a chest (or backpack, or an external inventory in general)
3. Right click the armor in the external inventory
4. You should now have a new armor

**Comment by GizmoTheGreen** [comment] 2020-12-31 08:30
Just ran into this myself. it completely overwrote my allthemodium armor with the armor I accidentally right clicked and wondered why it made that sound, only to find it duped that armor overwriting was I was wearing instead of swapping it.

**Comment by CJNiiva** [comment] 2021-01-01 07:40
fuck, I just wanted to try to see if it worked, but IT RUINED MY MINING GADGET WITH ALL THE UPGRADES! jesus, made a new instantly, just a minor inconvenience, but yeah, pretty game breaking, would have quit if I was on a public server

**Comment by GizmoTheGreen** [comment] 2021-01-02 10:08
I have no idea what mod adds this functionality but it would be nice if there is a config to disable it for now

**Comment by jeremiahwinsley** [comment] 2021-01-02 15:31
Duplicate of #634

**Closed** 2021-01-09 23:56 UTC
Labels: Bug
