### ISSUE TITLE
Fix for all dimension bugs; no nether, no ender dragon, minecolonies

### ISSUE THREAD

**Issue by ViRb3** [AllTheMods/ATM-6#437] opened 2020-11-28 12:48 UTC
Prior to https://github.com/MinecraftForge/MinecraftForge/pull/7513 being merged into Forge, dimensions were created improperly, leading to a bunch of issues such as:
- Ender Dragon not spawning - https://github.com/AllTheMods/ATM-6/issues/333
- Can't travel into any dimension, such as the Nether - https://github.com/AllTheMods/ATM-6/issues/137
- Cross-dimension biome mixing - https://github.com/AllTheMods/ATM-6/issues/305
- Overworld not recognized by mods - https://github.com/AllTheMods/ATM-6/issues/396

This was fixed in ATM 1.3.3, Forge 35.1.4. __Every new world created after these updates will work as expected.__ If you can reset your world, this is the simplest and most reliable fix.

For existing worlds, however, you have to manually clean the mess. Here I propose a "universal" solution that should get you back to working. At a very high level: take a newly generated `level.dat`, which holds proper dimension information, and use it with your existing world. Unfortunately, this fix will __not__ solve any problems for __existing__ chunks - if your Ender structures are missing, or if your biomes are mixed. The only solution there is to re-create the affected dimensions, and possibly use [mcaselector](https://github.com/Querz/mcaselector) to transfer over any important chunks.

:warning: __NOTE:__ The steps described below are for a __dedicated server__, not for single player. For the latter, there are some major differences:
- The world folder is not `world`, but `/save/New World`, where `New World` is your single player world's name
- Player information is not stored in a dedicated `playerdata` folder, but instead in a NBT structure `Data/Player` inside `level.dat`. You will most probably want to copy it over. See: https://github.com/AllTheMods/ATM-6/issues/437#issuecomment-735845097

Without further ado, here is the process:

1. Update to ATM6 1.3.3, which has the fixed Forge version 35.1.4
2. Stop the server
2. Use [NBTExplorer](https://github.com/jaquadro/NBTExplorer) to get the seed for the existing world
![image](https://user-images.githubusercontent.com/2650170/100516276-6afb4780-318b-11eb-88aa-ea0177fbf2d1.png)
3. Edit your `server.properties` and set the `seed=` to your old seed noted above
1. Rename the `world` folder with all of your world data to `world.bak`. __Create a zip of it as a second backup, just in case__
4. Start the server. A new, fresh, bug-free world will be generated in a new `world` folder
5. Stop the server
6. Copy over the `level.dat` from the new `world` to the old `world.bak`, replacing the old `level.dat`. Additionally, in the old `world.bak`:
    - Use NBTExplorer to re-apply any properties that may be important to you, such as the server time elapsed or game rules
    - If your end dimension is impacted by the ender dragon not spawning bug, delete your `DIM1` folder
    - If your nether dimension is impacted by the random biome bug, delete your `DIM-1` folder
    - If you can, delete any additional dimension folders, such as the whole `dimensions` folder
    - __Make sure you don't have anything important in the dimensions that you're deleting__
7. Delete or rename the new and now unneeded `world` folder
8. Rename the old world folder, `world.bak`, back to `world`
9. Restart the server. Everything should be fixed

We tested this on our server and it worked great. Hope it helps people.

**Comment by RickyvdBerg** [comment] 2020-11-28 13:28
Thanks a lot for looking into this and providing a solution. My world has been plagued by many of these issues, I am going to implement this fix now and report back when I have results

**Comment by GamingDestroyer** [comment] 2020-11-29 18:39
How is this done for a singleplayer world?

**Comment by ViRb3** [comment] 2020-11-29 18:41
The same procedure, except the folder is not `world`, but `/save/New World`, where `New World` is your single player world's name.

**Comment by RealTrueDeviL** [comment] 2020-11-30 14:03
Can I just add, take EVERYTHING off your character, into a chest, I just did this fix, lost everything I had on me, including a full set of ATM Armour, special weapon, the lot...

**Comment by ViRb3** [comment] 2020-11-30 14:06
Your character/player items are located in the `playerdata` folder. If you followed the instructions carefully, the only file that you will have changed is the `level.dat`, so your `playerdata` folder should be completely intact. Either way, if you made a backup you can simply restore it and try again.

**Comment by RealTrueDeviL** [comment] 2020-11-30 14:08
I thought it was seperate too, but my char is honestly wiped, all I have is the Astral Tome.. I did make a backup, so I'll just do it again.. :)

**Comment by RealTrueDeviL** [comment] 2020-11-30 14:29
Ok, seems level.dat hold player inventory data...
![Screenshot 2020-11-30 142826](https://user-images.githubusercontent.com/21058263/100622126-66b06500-3318-11eb-9867-436d0e21e27f.png)

**Comment by ViRb3** [comment] 2020-11-30 14:30
Is this a Single Player world by any chance?

**Comment by RealTrueDeviL** [comment] 2020-11-30 14:31
yes, I'm guessing that matters >.< however something to note?

**Comment by RealTrueDeviL** [comment] 2020-11-30 14:35
Either way, you can copy the player data, from the backup, to the new one in NBTExplorer, just remember to rename it correctly, and delted the old one..

**Comment by ViRb3** [comment] 2020-11-30 14:35
Interesting. I suppose it makes sense that everything would be in `level.dat` if there's just one player, but I didn't know that. Thanks for letting me know. I'm afraid that I haven't tested this in single player, so I can't help much. Obviously, you will at least want to copy-paste your whole `Player` structure from the old save. Please let me know how you end up making this work and if there's anything else you did, so I can update the main post.

**Comment by RealTrueDeviL** [comment] 2020-11-30 15:11
FOR SINGLE PLAYER:
----------------------

Make sure Minecraft isn't running..

Make a backup of your OLD level.dat, so you don't overwrite it, put it somewhere safe (desktop)..

The Copy from that (old level.dat) to the NEW level.dat..

Delete the original one, which should be Player: 43 entries..

Rename Tag - Player (Copy 1) to Player

Save, and restart MC

![Screenshot 2020-11-30 142826](https://user-images.githubusercontent.com/21058263/100626863-3a97e280-331e-11eb-84a9-c24a3dbe27ab.png)

Now it should work, and you'll have all your items..

**Comment by Devoidsoul675** [comment] 2020-12-01 13:37
Super helpful, thank you so much

**Comment by glahera** [comment] 2020-12-01 15:24
Very nice, thank you for your contribution. Back when server updated to 1.3.2c, I just told everyone on my server to migrate to mining dimension then delete every other dimensions (though The Other still doesn't generate any dragon...) and it works out fine for us.

**Comment by andrewsf** [comment] 2020-12-04 05:38
The issues with Ice and Fire are completely unrelated to the Forge dimension info bug that led to this problem.

And yes, your player data is only stored by UUID in `playerdata` if you are connecting to the server. If you are hosting the server (including single-player and local play open to LAN), then your data is in the level.dat file.

**Comment by RealTrueDeviL** [comment] 2020-12-04 08:15
> 
> 
> IMO the much better solution than copying things into a new level.dat file is to fix the old one.
> 
>     * open NBTExplorer with the existing level.dat
> 
>     * open NBTExplorer with a brand new level.dat
> 
>     * copy/paste the `WorldGenSettings/dimensions` entries for `the_end` and `nether` from the new level.dat file to the existing level.dat file
> 

Wait, so you're saying a 'better' solution, than copying things into a new level.dat... Is to copy things  OUT of a new level.dat, into your existing one... So no difference.. Either way works.. which means it's not better.. it's equal..

I'll give you points for trying to 1-up my solution tho...

**Comment by andrewsf** [comment] 2020-12-04 08:21
> So no difference.. Either way works.. which means it's not better.. it's equal..

Your house has a broken radiator. It's very cold. Would you prefer to get a new radiator and put it into your house? Or would you prefer to get a new house, and move everything out of your existing house?

If you know what specific things are wrong, fix those things. It's not likely you, modders, or even Mojang know every single thing in your old save file that needs to be mirrored to a fresh one to avoid data loss.

**Comment by RealTrueDeviL** [comment] 2020-12-04 08:28
Well, I was the one who fixed my single player, and put the solution here, which means, it worked perfectly fine, I still have all my waypoints, my save has my base, and everything's working as it should be..

Had zero side effects doing it my way..

ViRb3's solution was for servers, mine is for single player, hence why he asked me to put details of what I did to get it working... So.. Yeah, that is my solution.. Based on ViRbe's idea

**Comment by Lejoni** [comment] 2020-12-08 00:57
I did used this fix. And it worked fine, I could again go to the Nether and it looked much better than before.
But now again I can't zone to the Nether. Seams like something keeps breaking it.

**Comment by whatthedrunk** [comment] 2021-01-29 14:45
Going to keep this pinned for reference but close the issue for now. The new version of forge fixes this finally.

**Closed by whatthedrunk** 2021-01-29 14:45 UTC
Labels: Bug, Question, wont/cant fix

**Comment by exastencil** [comment] 2021-02-03 20:53
I'm not sure about the other problems, but I just had an End Dimension generate without an Ender Dragon or End Fountain in All the Mods 1.5.1 with Forge 36.0.9.

I tried deleting the End and regenerating it, but the same problem occurred: Obsidian spires generated with crystals but no dragon or fountain. Not sure what to do now.

**Comment by ViRb3** [comment] 2021-02-03 21:45
@exastencil This was a known issue with Forge 36.0.9 / ATM 1.5.0. Update to Forge 36.0.13 / ATM 1.5.1 and then regenerate your End dimension to fix it.

**Comment by exastencil** [comment] 2021-02-04 06:27
Hmm, updated to ATM 1.5.1 and Forge 36.0.13, regenerated my End dimension and still no dragon or fountain. Same as before.

**Comment by RealTrueDeviL** [comment] 2021-02-05 17:33
I've just checked my 'End' dimension after the 1.5.1 (ATM6) update, and I also have no Dragon, I've never killed him >.<

**Comment by Tops420** [comment] 2021-02-06 14:36
Same issue, End crystals don't summon the dragon.. Regenerating DIM1 fails to recreate the fountain (with level.dat also with edits to 0 for the dragon fight variables), fails to spawn the OG dragon also

**Comment by Tops420** [comment] 2021-02-07 05:53
Update to my previous post..

I fixed my issue. I had to create a fresh world using my seed, my old playerdata folder, specific MCA files in the region folder (located the ones i wanted to keep with MCAselector), certain configs i edited in the serverconfig folder, the data folder, mine colonies folder.. End was fully restored, end crystals work.. and also Nanonite Crystals started to appear from Environmental Tech Void Miner which wasn't generating previously. Hope this info is useful to someone

**Comment by RealTrueDeviL** [comment] 2021-02-07 12:13
> 
> 
> @exastencil This was a known issue with Forge 36.0.9 / ATM 1.5.0. Update to Forge 36.0.13 / ATM 1.5.1 and then regenerate your End dimension to fix it.

I can confirm, this method does not work, I used NBT Editor to change the 'killed' status back to 0, deleted Dim1, then started the game, got a new End, but no dragon or portal.. I didn't even go to the end when I had 1.5.0, I've not been there in a few updates, after I fixed it the 1st time..

Maybe I should try that fix again...

**Comment by skipgamer** [comment] 2021-02-08 02:21
My world was created with 1.4.9b and having this issue as of 1.5.1 Wasn't able to respawn the ender dragon and after deleting the end dimension to see if regenerating would fix it, the portal is completely missing.

**Comment by JheregJAB** [comment] 2021-03-05 23:04
Just got this issue in ATM6 1.5.1 with forge 36.0.13. My planned troubleshooting steps are to update to 1.5.3b first, then to delete the dimension for the end and try again. If that fails I will start looking into the other troubleshooting steps listed here.

Since I am way past the supposedly effected forge version I am not completely sure its the same issue.

**Comment by andrewsf** [comment] 2021-08-14 03:09
This issue is in a *Closed* state.
If you have newly encountered a problem, and you cannot prove that your symptoms have the same cause as this closed issue, create a new issue ticket with _all_ the relevant data.

**Comment by SteamDoge9000** [comment] 2021-11-27 01:42
ok I tried something and I found it to work

the best solution thought having todo anything super complex like what I have seen above

all you have todo is to edit these values in the Level.dat

![image](https://user-images.githubusercontent.com/38770780/143664289-2d8008db-33fe-44cf-b2a1-d4f63725dbdb.png)
idk what one it was, but all of these were set to one and when I reloaded the world after setting those 3 to zero, the portal frame regenerated

**Comment by Possemaster** [comment] 2021-12-30 15:42
Just remove all children of DragonFight, save the level.dat and restart the server will fix your Spawn issue in the END
![image](https://user-images.githubusercontent.com/7541145/147766353-c1498260-4dba-477e-a1a3-64318f5def43.png)
