### ISSUE TITLE
ATM6 Versions 1.7.8 and 1.7.9 Have a Trojan in Them!!!

### ISSUE THREAD

**Issue by Andwinn** [AllTheMods/ATM-6#2191] opened 2021-08-20 01:12 UTC
Hi, -

My name's Andwinn, and I was about to download and play the most recent version of ATM6  with my friends, and we went to install it and we both got a notification that Windows Defender detected a Trojan called Wacatac.B!ml 

I'm guessing maybe one of the new mods you guys added had a Trojan imbedded in it? I figured I should post here about it since you might be affected since you guys put together the pack, so make sure you run your antivirus and figure out what's putting this Trojan in the pack! Version 1.7.7 seems to be fine so it's definitely something that got added in 1.7.8

Good Luck, and thanks for all the hard work on the pack!

Best, -
Andwinn

**Comment by Xplodin** [comment] 2021-08-20 01:35
False positive

**Comment by jeremiahwinsley** [comment] 2021-08-20 01:50
Duplicate of #2179 - feel free to double check with VirusTotal or another virus scanning service.

**Closed by jeremiahwinsley** 2021-08-20 01:50 UTC

**Comment by Andwinn** [comment] 2021-08-20 04:26
I'm glad it's a false positive then, I hadn't even thought of that as being a possibility. Thanks for the quick response, then!! I'm glad you guys checked to make sure it wasn't a legitimate threat, hopefully whatever's causing it goes away so it doesn't scare anyone else lol, thanks again though!!
