### ISSUE TITLE
Simple Server Files startserver.sh fails with curl on Linux/Unix/Mac

### ISSUE THREAD

**Issue by LeadAssimilator** [AllTheMods/ATM-6#2335] opened 2021-09-12 06:19 UTC
**Describe the bug**
startserver.sh fails to download the server starter jar if only curl is available.

The script is invoking curl without -L so redirects are NOT followed and the url in the script of course is redirecting, thus breaking the download.  Please add the -L to the script so it works out of the box without having to modify it every time.

**To Reproduce**
1. Download any version of the simple server files zip to linux, unix or mac without wget installed (or force the script to use curl at step 4)
2. Unzip the zip
3. Change permissions on the startserver.sh
4. Run startserver.sh
5. Observe error similar to `Error: Invalid or corrupt jarfile serverstarter-2.0.1.jar`
6. Cat the serverstarter-2.0.1.jar (or whichever version was attempted to be downloaded)
7. Observe the contents of the file is an html document with a redirection notice
8. Delete the corrupted jar
9. Change the script to invoke curl additionally with -L
10. Run startserver.sh
11. Observe everything is working

**Comment by radiomike** [comment] 2021-09-15 08:10
Duplicate of #2311

**Closed** 2021-09-15 08:10 UTC
Labels: Bug
