### ISSUE TITLE
Crash At Launch

### ISSUE THREAD

**Issue by mrb0mbsh3ll** [AllTheMods/ATM-6#355] opened 2020-11-22 00:00 UTC
Cannot Pin Point the root cause.

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
2020-11-21 18:37:42,818 main WARN Advanced terminal features are not available in this environment
[18:37:42] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, MR_b0mb_sh3ll, --version, forge-35.0.18, --gameDir, /Users/chazs/Twitch/Minecraft/Instances/All the Mods 6 - ATM6 - 1.16.4 (1), --assetsDir, /Users/chazs/Twitch/Minecraft/Install/assets, --assetIndex, 1.16, --uuid, b1a277d97d8549ab9f0d656db998c81e, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --width, 0, --height, 0, --launchTarget, fmlclient, --fml.forgeVersion, 35.0.18, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115]
[18:37:42] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0_271 by Oracle Corporation
[18:37:43] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
Exception in thread "main" [18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: joptsimple.OptionArgumentConversionException: Cannot parse argument '/Users/chazs/Twitch/Minecraft/Install/assets' of option assetsDir
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:92)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at joptsimple.ArgumentAcceptingOptionSpec.convert(ArgumentAcceptingOptionSpec.java:277)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at joptsimple.OptionSet.valuesOf(OptionSet.java:223)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at joptsimple.OptionSet.valueOf(OptionSet.java:172)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.ArgumentHandler.lambda$processArguments$2(ArgumentHandler.java:65)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.ArgumentHandler.processArguments(ArgumentHandler.java:65)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.processArguments(TransformationServicesHandler.java:83)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:58)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: joptsimple.ValueConversionException: Directory [/Users/chazs/Twitch/Minecraft/Install/assets] does not exist
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at joptsimple.util.PathConverter.convert(PathConverter.java:28)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at joptsimple.util.PathConverter.convert(PathConverter.java:14)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at joptsimple.internal.Reflection.convertWith(Reflection.java:124)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:90)
[18:37:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 13 more

**Comment by ViRb3** [comment] 2020-11-22 11:12
Looks like dupe of #339.

**Closed** 2020-11-24 14:38 UTC
