### ISSUE TITLE
Server reliably failing to save chunks in unloaded dimensions

### ISSUE THREAD

**Issue by Gerdathlete** [AllTheMods/ATM-6#1247] opened 2021-03-20 02:19 UTC
Recently I've noticed that builds on my server in RFTools dimensions and in Compact machines are disappearing and rolling back quite frequently. I'm running ATM6 version 1.5.5 and this is the error message that has been filling my server console feed:
https://pastebin.com/15qMZ3Bp

EDIT: The error messages also seem to appear in all other dimensions, including the nether.

**Comment by limpikus** [comment] 2021-03-20 18:07
Yep, i have same problem. And some lags with machines. 
https://pastebin.com/WQAMtung

**Comment by Miccolo02** [comment] 2021-03-20 21:02
Same problem with me. Even with a new game.

https://pastebin.com/vxgdw0kJ

**Comment by jeddell** [comment] 2021-03-20 22:40
Yep, Same problem. New, Updated server to 1.5.5

https://pastebin.com/jffZVMEk

**Comment by futuristickirito** [comment] 2021-03-21 11:24
Same problem but also loaded dimensions on 1.5.5

**Comment by RipperRoo12** [comment] 2021-03-21 11:32
I am also running into this issue and I think it might be a reason for bee duplication that started happening with 1.5.5. The amount of bees eventually brought the server to its knees).

**Comment by didis54** [comment] 2021-03-21 23:47
It is caused by appliedenergistics2:8.3.0-alpha.2, rollback to appliedenergistics2:8.3.0-alpha.1
or wait for next version to come up

**Comment by Gerdathlete** [comment] 2021-03-21 23:57
I don't even use AE2... Sucks in comparison to refined storage. I honestly think it should be removed until the mod is stable. Speaking of mods that are unstable: RFTools Dimensions has already caused me to crash over 4 times, and has almost crashed my server on many occasions since there seems to be no block blacklist for things like snow layers and gravity affected blocks that can cause spontaneous block update reactions.

**Comment by Pdiddy973** [comment] 2021-03-26 16:15
Fixed in 1.5.6 by rolling back to AE2 Alpha 1

**Closed** 2021-03-26 16:15 UTC
