### ISSUE TITLE
[Bug]: Immersive Engineering Tool Recipes (Hammer and Wire Cutters) don't work with damaged tools

### ISSUE THREAD

**Issue by connorb777** [AllTheMods/ATM-6#2544] opened 2021-10-09 15:03 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

The immersive engineering recipes for crafting with the engineer's hammer or wire cutters will only work with brand new tools. After crafting 1 item, the tool becomes damaged and the recipe no longer works. 

### latest.log

https://gist.github.com/connorb777/062e8f818b76d9868b31750b2debb26d

**Comment by DavidieHD** [comment] 2021-10-10 16:20
Duplicate of #2456

**Closed as completed** 2021-10-18 06:19 UTC
Labels: Bug
