### ISSUE TITLE
Crash when attacked by endermite, while wearing a specific armor enchant.

### ISSUE THREAD

**Issue by FedeKhan** [AllTheMods/ATM-6#524] opened 2020-12-08 17:41 UTC
[crash-2020-12-08_18.33.17-server.txt](https://github.com/AllTheMods/ATM-6/files/5660823/crash-2020-12-08_18.33.17-server.txt)
As accurately described by this report of 15 days ago : 
https://github.com/AllTheMods/ATM-6/issues/374
The issue is still causing the game to crash and loop, until a backup is restored.
I will also provide my crash report.

if the mods can confirm their knowing of the issue i will proceed to delete this post.

**Comment by ViRb3** [comment] 2020-12-22 00:11
Dupe of #374

**Closed by ViRb3** 2020-12-22 00:11 UTC
Labels: Bug
