### ISSUE TITLE
(Version 1.5.1) Biomes O'Plenty biomes generating in non-BOP worlds

### ISSUE THREAD

**Issue by GanaramInukshuk** [AllTheMods/ATM-6#1035] opened 2021-02-08 16:19 UTC
**Describe the bug**
Nether biomes specific to Biomes O'Plenty generate even if the world type is set to Default (IE, BOP is not enabled and only biomes from Oh The Biomes You'll Go will generate instead).

**To Reproduce**
1. Generate a new world with world type of default.
2. Go to nether.
3. Search any BOP nether biome (EG, Crystalline Chasm or Visceral Heap) using the nature's compass. The compass will successfully find a biome.
4. In comparison, searching any BOP overworld biome (EG, BOP Alps, Golden Prairie, or Rainforest) should fail to find any BOP biomes. Searching for any BYG biome should work.

**Screenshots**
The two screenshots demonstrate the bug reproduction process. The seed is to prove that the two screenshots are from the same world, and the biome searched is the BOP Alps, not the BYG Alps.
![2021-02-08_07 47 02](https://user-images.githubusercontent.com/5506045/107245902-87fe9300-69e4-11eb-9170-d8aa4134a05e.png)
![2021-02-08_07 47 39](https://user-images.githubusercontent.com/5506045/107245916-8c2ab080-69e4-11eb-81db-112ce59fed87.png)

**Additional context**
Discussions on world generation on Reddit describes using BOP may lead to "a straight line where the biome stops but nothing game breaking". Whether this was describing nether biome generation is unclear. (As an aside, both BOP and BYG have overlapping and therefore arguably redundant biomes.)
https://www.reddit.com/r/allthemods/comments/km1rhx/should_i_use_biomes_o_plenty_world_generation_for/

This may be tangentially related to issues regarding mismatched biome IDs or custom biomes failing to generate.
https://github.com/AllTheMods/ATM-6/issues/731
https://github.com/AllTheMods/ATM-6/issues/710

Similarly, upgrading from 1.4.1 to 1.5.1 (and possibly from 1.4.1 to 1.5.0 to 1.5.1) produces a similar biome mismatch.
![2021-02-08_08 18 15](https://user-images.githubusercontent.com/5506045/107247519-36570800-69e6-11eb-9fb7-b801bbe947e0.png)

The "nuclear" option may be to remove BOP outright, but if it can be resolved without resorting to that, one fix is to simply regenerate the nether.

**Logs**
No logs.

**Comment by CorgiTaco** [comment] 2021-02-08 19:58
This is expected behavior. In byg we take in all biomes both datapack and modded from the registry. This can be fixed in the byg-world config by adding it to the blacklist

**Comment by GanaramInukshuk** [comment] 2021-02-09 10:33
So it turns out, in investigating a similar issue with a different modpack ( https://github.com/NillerMedDild/Enigmatica6/issues/1075 ), I may have found the exact issue for why biome generation is inconsistent between versions: NBT data within level.dat changing between versions.

Screenshots below are my main world's backups, one from 1.4.1 (top) and 1.5.0 (bottom). The same behavior of biome generation changing between versions was observed there, too. (Also, the nether's biome_source had three entries in 1.4.1 that somehow became two in 1.5.0.)

<img width="198" alt="capture_nbt_1 4 1" src="https://user-images.githubusercontent.com/5506045/107348164-8b912900-6a7b-11eb-8ce6-76d1d6933677.PNG">
<img width="207" alt="capture_nbt_1 5 0" src="https://user-images.githubusercontent.com/5506045/107348172-8d5aec80-6a7b-11eb-91aa-ac29d0debece.PNG">

Since my main world has both BOP and BYG biomes, I'm under the impression that there's a corresponding BOP generation setting for both the end and nether, or something similar. Basically, BYG worlds shouldn't be using BOP biomes and BOP+BYG worlds probably shouldn't be using BYG's settings.

This finding isn't exhaustive since this is with a BYG+BOP world, not a BYG-only world. Also, this is technically two separate bugs now: BYG-only worlds generating BOP biomes and a BOP+BYG world inconsistently generating nether biomes across modpack versions.

**Comment by whatthedrunk** [comment] 2021-02-10 23:21
Yeah this is intended to happen. Use the blacklist to disable anything you dont want to see.

**Closed by whatthedrunk** 2021-02-10 23:21 UTC
Labels: Bug
