### ISSUE TITLE
Infinite Mekanism fluorite with Elemental Craft Version 1.5.2

### ISSUE THREAD

**Issue by arshiahf** [AllTheMods/ATM-6#1090] opened 2021-02-18 07:04 UTC
It's possible to make infinite fluorite by combining the ore purifier of Elemental Craft with the enrichment chamber/combiner of Mekanism.
1 Fluorite Ore -> 2 Purified Fluorite Ore (Ore Purifier)
1 Purified Fluorite Ore -> 5 Fluorite (Enrichment Chamber) (Total of 10 at this point)
1 Fluorite -> 1 Fluorite Dust (Crusher)
8 Fluorite Dust + 1 Cobblestone -> 1 Fluorite Ore
Leaves 2 Fluorite remaining after whole process, allowing an infinite creation loop.

![2021-02-18](https://user-images.githubusercontent.com/11847119/108318236-790aa400-718d-11eb-8f7c-0c14852f0b03.png)
![2021-02-18 (1)](https://user-images.githubusercontent.com/11847119/108318250-7d36c180-718d-11eb-9ed5-26da6f0c587a.png)
![2021-02-18 (2)](https://user-images.githubusercontent.com/11847119/108318258-80ca4880-718d-11eb-8189-74a86ea478d3.png)
![2021-02-18 (3)](https://user-images.githubusercontent.com/11847119/108318261-82940c00-718d-11eb-91b7-055d46f38019.png)

**Comment by arshiahf** [comment] 2021-02-18 07:06
Also applies to Diamond Ore and Emerald Ore using the same method

**Comment by TBoshoven** [comment] 2021-02-19 15:25
Dupe of #856 
Also applies to Nether Quartz

**Comment by Sirttas** [comment] 2021-02-20 15:36
fixed in elemental craft 2.5.12

**Comment by Pdiddy973** [comment] 2021-03-27 03:49
Should be fixed in 1.5.6

**Closed by Pdiddy973** 2021-03-27 03:49 UTC
Labels: KubeJS
