### ISSUE TITLE
Unknown trait serializer silentgear:stellar

### ISSUE THREAD

**Issue by R4GN4R92** [AllTheMods/ATM-6#1743] opened 2021-06-02 13:45 UTC
Hi, I'm using pack version 1.6.3b on my server from ZAP Hosting.
Everytime me or a friend of mine, try to connect to the server, e get:

"Failed to connect to the server Internal Exception: java.lang.IllegalArgumentException: Unknown trait serializer silentgear:stellar"

I tryed to delete the trait in the silentgear mods folder on server and client side, but then I get a Channellist missmatch.
Did anyone experience the same issue?

Best regards
Ragnar

**Comment by bbaaxx** [comment] 2021-06-04 06:28
I am getting the same with version 1.6.5. 
Seems like a mod version mismatch caused by the server script downloading the latest version of the Silent Gear mod. The problem seems to be fixed on 1.6.7 but if the Silent Gear developers release an upgrade, the server script may break again.

**Closed** 2021-06-08 08:00 UTC
Labels: Bug

**Comment by m0rtis0** [comment] 2021-07-06 12:55
Same issue here
