### ISSUE TITLE
Music randomly plays and stops shortly after 

### ISSUE THREAD

**Issue by Odey555** [AllTheMods/ATM-6#1948] opened 2021-07-04 07:15 UTC
**Describe the bug**
Music will randomly start playing. Music in options turned off. Shortly after it starts (usually within 10 seconds) it suddenly cuts off. This happens randomly and not super often but its still kinda annoying. Most interesting part I'm playing with 2 friends on my server and we hear the music start & stop at the exact same time. Uploading both server and client logs if it helps 
1.6.14, only extra mod installed is OptiFine (though I doubt its relevant to this bug) 
**Logs** 
[Client and server-side logs](https://gist.github.com/Odey555/31d90a24d0037d224d1d6ec00a4e1ef2)

**Comment by radiomike** [comment] 2021-07-04 09:16
Not %100 sure on this, but it's likely to be caused sophisticated backpacks. Mobs can spawn with jukebox backpacks.

**Comment by P3pp3rF1y** [comment] 2021-07-04 15:03
Yeah it's very likely sophisticated backpacks. 
What's the volume of the music? Same level and what seems to be a max level for music disc?
Would you be able to identify what mod that music disc is from?

I am pretty sure it's caused by mod's music disc playing music in stereo - that causes the sound engine that mc uses play it at max level whatever the distance to the sound source. So a mob spawns with jukebox upgrade and this disc in it and because it spawned far away from player it despawns during those 10 seconds but because the sound ignores distances it plays at player locations as if the mob was right there.
I had the same happening with one other mod and was fixed by mod providing music in mono that can actually get quietter over distance.

**Comment by radiomike** [comment] 2021-07-04 15:35
That sounds about right. There is a setting in the config for the mod to disable it. Not sure if it needs to be done on both client and server though.

**Comment by Odey555** [comment] 2021-07-04 21:07
> Yeah it's very likely sophisticated backpacks.
> What's the volume of the music? Same level and what seems to be a max level for music disc?
> Would you be able to identify what mod that music disc is from?
> I had the same happening with one other mod and was fixed by mod providing music in mono that can actually get quieter over distance.

Music volume is pretty much as if I'd started playing a music box. As for the music, its just the vanilla music/ soundtrack. 
I'll see if I can disable it in server config without everything breaking heh

**Comment by P3pp3rF1y** [comment] 2021-07-05 17:15
I was just playing ATM6 for a bit and had this occurence of music playing which really is minecraft music not one from vanilla music discs. Found that rats add two music discs that just reference default minecraft music and there lies the issue - the default music is in stereo so it's not suitable to be played on a music disc because stereo music when played as a disc is global (distance doesn't affect its volume and thus it can be heard at the same volume however far you are from the jukebox and because of that also all of the players are in its range). This happens whether you play the disc in backpack or with just vanilla jukebox.

The real solution here is for rats to include music for the discs that's in mono so that it can change volume with distance from jukebox. Short term "solution" just for mobs with backpacks is to ban these two discs in SBP config
In `discBlockList` just add records for `rats:music_disc_mice_on_venus' and `rats:music_disc_living_mice'.

**Comment by tekkitan** [comment] 2021-07-05 17:38
This problem was happening to me before sophisticated backpacks was added. I noticed when the music seems to have a central location, like you move around and changes how you hear it, then it is a mob with sophisticated backpacks. But then music will start playing without any kind of location, the volume of it does not change while moving around, and this has been happening to me since before 14.

**Comment by BovineShaman** [comment] 2021-07-09 05:44
Fixed in next update.

**Closed by BovineShaman** 2021-07-09 05:44 UTC
Labels: Bug
