### ISSUE TITLE
[Bug]: ATM6 1.16.5 - Client Disconnect when joining server

### ISSUE THREAD

**Issue by Aavar6802** [AllTheMods/ATM-6#2489] opened 2021-10-03 14:33 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

New client install disconnects after "Loading terrain..." is shown, the error after disconnect is `internal exception io.netty.handler.codec.decoderexception: java.lang.nullpointerexception`. As seen on the client logs, `[Render thread/FATAL]: Error executing task on Client java.util.NoSuchElementException: packet_handler`

Server-side, the disconnect happens after: `[Server] Server thread/INFO [mc.li.se.DefaultModSetup/]: Client logged in: sending dimlet packages`.

Restarting the server allows the client to log in. As long as the client launcher remains open, you can connect. If the client launcher is closed and restarted, the same issue occurs. Server restart, again, fixes the issue. 

### latest.log

https://gist.github.com/Aavar6802/c735140511ba1ac3f4a31e788064dca8

**Comment by Aavar6802** [comment] 2021-10-04 21:27
If you launch a single-player world after receiving the internal exception error you are able to log into the multiplayer world with no issues. Seems to point to a client-side issue in 1.8.4

**Comment by ladylexxie** [comment] 2021-10-05 12:43
Duplicate of #2407

**Closed by ladylexxie** 2021-10-05 12:43 UTC
Labels: Bug
