### ISSUE TITLE
[<=1.3.9b..1.4.1]Recipe missing - Mystical Agriculture rubber seed

### ISSUE THREAD

**Issue by Slaymeister** [AllTheMods/ATM-6#905] opened 2021-01-20 22:43 UTC
Issue
The recipe to craft Mystical Agriculture seed is missing. (mysticalagriculture:rubber_seed) The seed itself does exist, including it being a possible product of the growth of the seed itself, but the infusion crafting recipe is not there.

You can reproduce this by checking NEI, and comparing the rubber seeds to any other Mystical Agriculture seed entry.

Screenshot
NEI Entry for rubber seeds
<a href="https://imgur.com/ryGhn51"><img src="https://i.imgur.com/ryGhn51.png" title="source: imgur.com" /></a>

NEI Entry for silicon seeds for comparison
<a href="https://imgur.com/fFBt8kZ"><img src="https://i.imgur.com/fFBt8kZ.png" title="source: imgur.com" /></a>

**Comment by Slaymeister** [comment] 2021-01-21 08:43
BTW, I ran into this bug in 1.3.9b before updating to 1.4.1.  Not sure that's relevant, other than it wasn't caused by a recent change.

**Comment by Slaymeister** [comment] 2021-01-30 17:41
Some additional information, several Mystical Agriculture recipes seem to be broken in one of two ways.  The first is a missing crafting recipe as initially reported here. This may be intentional - I can't tell. The other is broken recipes, such as silicon seeds. The infusion crafting is done with essence, a unique component, and a seed base. The broken recipes miss the unique component and leave only the essence and seed base. These partial recipes do not work.

What's the process for creating pull requests to fix these? Can I just create a fix and submit it or is there a process?

**Comment by thevortex** [comment] 2021-01-30 20:52
That would be awesome if you can do that :)

**Comment by WhitePhant0m** [comment] 2021-02-02 21:59
> 
> 
> Some additional information, several Mystical Agriculture recipes seem to be broken in one of two ways. The first is a missing crafting recipe as initially reported here. This may be intentional - I can't tell. The other is broken recipes, such as silicon seeds. The infusion crafting is done with essence, a unique component, and a seed base. The broken recipes miss the unique component and leave only the essence and seed base. These partial recipes do not work.
> 
> What's the process for creating pull requests to fix these? Can I just create a fix and submit it or is there a process?

To my knowledge, the recipes are only visually broken, and they work if you just use the components that it would need(silicon for silicon seeds), and there isn't really any rubber in the pack, so rubber seeds don't make anything or aren't crafted with anything(it uses tags, so if there is rubber, blame mod makers for not tagging it)

**Comment by WhitePhant0m** [comment] 2021-02-02 22:18
Also, duplicate of #775

**Closed by WhitePhant0m** 2021-02-02 22:18 UTC
Labels: Bug
