### ISSUE TITLE
Cannot Join Server.  Anyone know what this Internal Exception means? Help!?

### ISSUE THREAD

**Issue by ZaneInvictus** [AllTheMods/ATM-6#1142] opened 2021-02-28 20:03 UTC
Hello!  Trying to connect to a friends server. All The Mods 6: 1.5.3  Keep getting this error:

Internal Exception: net.Minecraft.util.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: nslate":"trait.silentgear.adamant"}-{"translate":"trait.silentgear.adamant.desc:}  then some symbols, then armor ... mine.

![image](https://user-images.githubusercontent.com/79808788/109431549-3179e880-79d5-11eb-864e-500884fd9a72.png)

Any ideas?  I'm the only one getting this, as everyone else connects no problem.

Thanks!

**Comment by MaoamDEV** [comment] 2021-02-28 20:20
Can you provide some more information please?

- Have you tried to reinstall the modpack?
- Can you provide your client log?
- Did you started with a fresh 1.5.3 install, or did you updated?

Sounds pretty much like a broken JSON-file.

**Comment by thevortex** [comment] 2021-02-28 20:22
Try reinstalling the latest version of the pack(fresh instance)

**Comment by ZaneInvictus** [comment] 2021-02-28 20:42
Thanks for the replies!  So I tried playing from a fresh install.  Then deleted, reinstalled, and still get the internal exception.  Here's a log.  Hope this is what u mean.  Never done this before.

https://paste.ubuntu.com/p/fsrJJn2vCm/

**Comment by ZaneInvictus** [comment] 2021-02-28 20:47
Hope THIS does it.  Woops!  Looked like that link didn't copy/show all of the log.  Here it is copied.

15:39:07.465
net.minecraftforge.fml.network.NetworkRegistry
Netty Client IO #3
Channels [alexsmobs:main_channel,libx:netchannel,endertanks:main_channel,minecolonies:net-channel,silentgear:network,tombstone:tombstone_channel,pneumaticcraft:main_channel] rejected their server side version number during listping
15:39:07.466
net.minecraftforge.fml.client.ClientHooks
Netty Client IO #3
Server has additional mods that may be needed on the client: emojiful@1.16.4-2.1.4
15:39:07.467
net.minecraftforge.fml.client.ClientHooks
Netty Client IO #3
Client has mods that are missing on server: [supermartijn642configlib, alexsmobs, simplemagnets, integratedterminals, mcwwindows, rftoolsbase, powah, randompatches, darkutils, jeresources, mysticalagradditions, shetiphiancore, industrialforegoing, repurposed_structures, ironfurnaces, silentgear, tombstone, globalxp, geckolib3, woot, mekanism, compactmachines, libx, phosphophyllite, pneumaticcraft, iceandfire, ars_nouveau, mythicbotany, allthemodium, rftoolsbuilder, integrateddynamics, integratedterminalscompat, structurize, kubejs_create, pickletweaks, aquaculture, extremesoundmuffler, cosmeticarmorreworked, xpbook, cyclopscore, advancedperipherals, glassential, configurableextramobdrops, citadel, ftbguilibrary, culinaryconstruct, buildinggadgets, mekanismgenerators, xnetgases, absentbydesign, resourcefulbees, commoncapabilities, endertanks, entangled, mekanismadditions, lollipop, dpanvil, patchouli, rftoolsstorage, collective, camera, lostcities, ftbultimine, mekanismtools, architectury, trashcans, cyclic, betteradvancements, biggerreactors, cucumber, itemfilters, elementalcraft, platforms, clumps, appliedenergistics2, travel_anchors, mahoutsukai, integrateddynamicscompat, recipebuffers, mysticalagriculture, rftoolsutility, titanium, mana-and-artifice, ctiers, quark, enderchests, minecolonies, engineersdecor]
15:39:11.066
Astral Sorcery
Render thread
Client cache cleared!

**Comment by MaoamDEV** [comment] 2021-02-28 20:57
Based on the reports this is a version mismatch of client and server.

Server got Emojiful installed which got removed in 1.5.3 and the client has many mods that the server lacks. Pretty sure that the server isn't up to date with 1.5.3 installed. Please reach out to your friend who is hosting and clarify the version with him.

**Comment by ZaneInvictus** [comment] 2021-02-28 21:00
Thanks!  We thought it was the 1.5.3, and it turns out the server is on 1.5.2.  Reinstalling older version, and then I'll try.  Alot of effort and he gave me the WRONG DANG VERSION. lol

Well thank you for your help!

**Comment by MaoamDEV** [comment] 2021-02-28 21:04
You're welcome! Just make sure to close the issue if the problem is solved with the correct version. :)

**Comment by ZaneInvictus** [comment] 2021-02-28 21:05
Ok, will do.  Never used github before.  Ty for the heads up.

**Closed** 2021-02-28 22:33 UTC
