### ISSUE TITLE
[Crash]: Full set living armor crashes game in server

### ISSUE THREAD

**Issue by kalenm** [AllTheMods/ATM-6#2705] opened 2021-11-18 17:20 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

When equiping all the pieces of living armor from blood magic the game crashes when playing on a server. The armor works fine in single player. 

### Crash Log

https://gist.github.com/kalenm/62e7579e13fb84211b323c6827d60b52

**Comment by jeremiahwinsley** [comment] 2021-11-18 22:13
Duplicate of https://github.com/AllTheMods/ATM-6/issues/2628

**Closed by jeremiahwinsley** 2021-11-18 22:13 UTC
Labels: Crash
