### ISSUE TITLE
Nether does not work.

### ISSUE THREAD

**Issue by Bearman1989** [AllTheMods/ATM-6#341] opened 2020-11-19 23:17 UTC
**Describe the bug**
After updating my server yesterday, I am unable to get to the nether via the portal or a waystone.  The portal will just do the animation but not port, and the waystone option is there but nothing happens when you click it.

**To Reproduce**

**Expected behavior**
I expected to be brought to the nether.
**Screenshots**

**Additional context**
The server was just updated to the newest version.

**Comment by NoMoreStars** [comment] 2020-11-19 23:30
Just encountered the same problem, looks like it's a duplicate of #137.

**Comment by whatthedrunk** [comment] 2020-11-20 22:43
https://github.com/AllTheMods/ATM-6/issues/137

**Closed by whatthedrunk** 2020-11-20 22:43 UTC
Labels: Bug
