### ISSUE TITLE
Crafting Chests (Only works with logs)

### ISSUE THREAD

**Issue by Explode007** [AllTheMods/ATM-6#868] opened 2021-01-16 15:05 UTC
Latest Pack Version 1.4.0
**Crafting recipe for chests with normal wood planks doesn't work, only logs crafting recipe exists**

**To Reproduce**
1. Load a world
2. Try to craft chest or look at recipe in JEI
3. Realize it don't work
4. Cry cause you can only make chests in bulk

**Screenshots**
![image](https://user-images.githubusercontent.com/12020284/104815392-a066fd80-57ea-11eb-95e4-a347448c662c.png)
![image](https://user-images.githubusercontent.com/12020284/104815398-a9f06580-57ea-11eb-98e7-72d356adfb64.png)
![image](https://user-images.githubusercontent.com/12020284/104815401-b4126400-57ea-11eb-87ac-293c601331a9.png)

**Comment by jeremiahwinsley** [comment] 2021-01-16 16:34
Duplicate of #853

**Closed by jeremiahwinsley** 2021-01-16 16:34 UTC
Labels: Bug
