### ISSUE TITLE
Lightning problems

### ISSUE THREAD

**Issue by przemykomo** [AllTheMods/ATM-6#10] opened 2020-07-18 13:12 UTC
![screenshot](https://i.imgur.com/WHlmEHp.png)
As you can see on the screenshot, when I log into the server light is broken only in one location. In other locations everything works correctly. This happened to me several times in the same location and never in different locations. Only breaking and placing torches again fixes it (until I log into the server again).

**Comment by whatthedrunk** [comment] 2020-07-21 23:42
Duplicate of #8

**Closed by whatthedrunk** 2020-07-21 23:42 UTC
