### ISSUE TITLE
Crash in the other dimension

### ISSUE THREAD

**Issue by Photatoke** [AllTheMods/ATM-6#715] opened 2021-01-02 19:52 UTC
Whenever i load a certain chunk in "the other" dimension its crashes the server instantly. Sometimes the player too

Crashreport: https://pastebin.com/CjV1PFjZ

Also, i have added a few mods in the modpack but that shouldn't affect the crash.

**Comment by jeremiahwinsley** [comment] 2021-01-02 19:58
Duplicate of #696

**Closed** 2021-01-09 23:35 UTC
