### ISSUE TITLE
[1.5.10b] Multiservo Press deleting Woot processing Die's.

### ISSUE THREAD

**Issue by Zargachi** [AllTheMods/ATM-6#1424] opened 2021-04-14 14:00 UTC
**Describe the bug**
The Multiservo Press from Thermal Series mod is essential for some automations, that said, it have some recipes to automate Woot craftings, for example the Mob Shard and the Color Dye Casing, for those crafts, the Multiservo Press uses a shape, and for some reason those shapes are consumed on the crafting, you can use those same shapes to mannually craft those items but in this case the shape is not consumed, automated crafters also don't cosume it, i tested the shapes from Thermal Series and they also are not consumed, in resume, there is something wrong on how the Multiservo Press do this processing, also, theses shapes from Woot can't be crafted automatically as far as i know, because they are made manually in a special and unique crafting grid from the mod.

**To Reproduce**
1. In a Multiservo Press put a Shard Die or a Dye Casing Die from Woot mod.
2. Put a Ender Pearl for the Shard Die or any vanilla dye for the Dye Casing Die to be processed.
3. Waint until the processes is finished
4. The Shard Die or Dye Casing Die should disappear after the processing is completed.

**Additional context**
This machine was working propperly as far as i know and for some reason started this bug, i tryed making a new machine and the problem persisted, the Die's are not been ejected to a container or something like that as bi-product, they are just beeing deleted.

**Comment by ladylexxie** [comment] 2021-07-09 05:40
Duplicate of #1423

**Closed by ladylexxie** 2021-07-09 05:40 UTC
Labels: Bug
