### ISSUE TITLE
Vibranium Ore not spawning in the nether v1.4.0

### ISSUE THREAD

**Issue by dannieth** [AllTheMods/ATM-6#898] opened 2021-01-19 19:56 UTC
Vibranium Ore does not generate in the nether in worlds created with version 1.4.0. I have checked both on my server and 5 separate brand new singleplayer worlds using vibranium sight and spectator mode. 

**To Reproduce**
1. Create new World
2. Go to Nether

**Comment by Pdiddy973** [comment] 2021-01-19 20:14
Duplicate of #862

**Closed** 2021-01-19 20:14 UTC
Labels: Bug
