### ISSUE TITLE
Ice and fire doesnt spawn

### ISSUE THREAD

**Issue by RidleyistheBest** [AllTheMods/ATM-6#342] opened 2020-11-19 23:43 UTC
**Describe the bug**
Ice and fire wont spawn in the overworld, on server and singleplayer

**Expected behavior**
Ice and fire mobs shouldve spawned

**Additional context**
we tried downgrading the version doesnt work
we also travelled 5000 blocks away as suggested by another user and this wont work aswell changing the config is too complicated for us

Edit:
Other dimensions like the other and mining dimension won't work either

Ive seen other people complain but its only a handfull

**Comment by NoahHagberg** [comment] 2020-11-20 00:26
I think you're supposed to use the teleport pad which will take you to the mining dimension when used from the overworld (or the "other" dimension if used from the nether) and there they'll spawn.

**Comment by RidleyistheBest** [comment] 2020-11-20 07:27
> I think you're supposed to use the teleport pad which will take you to the mining dimension when used from the overworld (or the "other" dimension if used from the nether) and there they'll spawn.

nope other users tried it doesnt seem to work. and also we dont know how to activate it in the overworld but it seems it generally doesnt work 

we're using the 1.3.0. version of the pack

**Comment by RidleyistheBest** [comment] 2020-11-20 09:56
> I think you're supposed to use the teleport pad which will take you to the mining dimension when used from the overworld (or the "other" dimension if used from the nether) and there they'll spawn.

yeah just checked to be sure no structures and no mobs spawn in either dimensions

**Comment by Treep3r** [comment] 2020-11-20 18:21
According to this the mod itself had a problem, which has been fixed now.
https://github.com/Alex-the-666/Ice_and_Fire/issues/3110#issuecomment-730650272
The only thing that's left to do is update the config for ATM6 (since it's custom), which I unfortunatly have no idea how to do properly.

**Comment by RidleyistheBest** [comment] 2020-11-21 13:44
> According to this the mod itself had a problem, which has been fixed now.
> [Alex-the-666/Ice_and_Fire#3110 (comment)](https://github.com/Alex-the-666/Ice_and_Fire/issues/3110#issuecomment-730650272)
> The only thing that's left to do is update the config for ATM6 (since it's custom), which I unfortunatly have no idea how to do properly.

Oooh thanks my friend least we're a bit closer to fixing it now 
@Treep3r

**Comment by ViRb3** [comment] 2020-11-24 18:13
Dupe of #356.

**Closed by ViRb3** 2020-11-24 18:13 UTC
Labels: Bug
