### ISSUE TITLE
AllTheOres Lead incompatible with Eidolon Mind-Shielding Plate

### ISSUE THREAD

**Issue by mooproxy** [AllTheMods/ATM-6#1271] opened 2021-03-23 20:20 UTC
ATM6 1.5.5
**Describe the bug**
Eidolon mind-shielding plate cannot be crafted. Only difference between the recipe in JEI and my application is that JEI recommends Eidolon-specific lead ingots whereas I am using AllTheOres lead.

**Comment by ladylexxie** [comment] 2021-07-09 04:23
Duplicate of #928

**Closed by ladylexxie** 2021-07-09 04:23 UTC
Labels: Bug
