### ISSUE TITLE
Singleplayer quit to Multiplayer Screen

### ISSUE THREAD

**Issue by krabbbbe** [AllTheMods/ATM-6#860] opened 2021-01-16 10:57 UTC
False directing when quitting Singleplayer.

1. Play Singleplayer World
2. Quit (Save & Exit)  Singleplayer World
3. Get directed to the Multiplayer screen/Server Selection

Appeared in the versions 1.3.6 and newer as well.

**Comment by Pdiddy973** [comment] 2021-01-16 11:01
Duplicate of #730

**Closed** 2021-01-16 11:02 UTC
Labels: Bug
