### ISSUE TITLE
[Bug]:  Applied energistics double crafting and not leaving autocraft screen.

### ISSUE THREAD

**Issue by TheAnimaDust** [AllTheMods/ATM-6#2503] opened 2021-10-04 10:22 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.5

### What happened?

After the update Applied autocrafting is double crafting items and doing strange things, besides that the only function working on the new wireless terminal are the infinity range, i can't request any autocraft unless in range of one of the transmitters and the crating grid on the terminal don't work. also after you click start to make an autocraft sometimes the hud don't return to the inventory and just stay there you need to return manually to the inventory. Before the update everything was working fine.

The world was generated on 1.6.4 and the server was updated to 1.6.5.

### latest.log

https://gist.github.com/TheAnimaDust/f51fdd748218224d3c1839db220ab177

**Comment by ladylexxie** [comment] 2021-10-04 11:59
I'm assuming you meant to say 1.8.4 and 1.8.5?

**Comment by guzinhu** [comment] 2021-10-04 12:44
That is caused by Applied Energistics 2 Wireless Terminals, to fix just remove the mod from mods paste

**Comment by guzinhu** [comment] 2021-10-04 14:59
> That is caused by Applied Energistics 2 Wireless Terminals, to fix just remove the mod from mods paste

mods folder*

**Comment by TheAnimaDust** [comment] 2021-10-04 15:38
Yes i mean 1.8.4 and 1.8.5 sorry =="

**Comment by DavidieHD** [comment] 2021-10-04 19:09
yup i have the same issue

**Comment by ladylexxie** [comment] 2021-10-05 12:47
Will be fixed in the next version by removing the mod as it's not working and has many issues.

**Closed by ladylexxie** 2021-10-05 12:47 UTC
Labels: Bug

**Comment by sh4ni** [comment] 2022-01-01 17:37
Please report this bug to the Mod Author. I wan't Wireless Terminals back, so this needs to get fixed.

**Comment by EverardNisse** [comment] 2022-01-09 10:36
The mod maintainer has been working on a fix here, please test / include when there is a release
https://github.com/Tfarcenim/AE2WirelessTerminalLibrary/issues/27
