### ISSUE TITLE
 Server Crash Exception Ticking World

### ISSUE THREAD

**Issue by violetkitty87** [AllTheMods/ATM-6#75] opened 2020-08-19 20:20 UTC
https://pastebin.com/X6PRrER9

Any time a specific player gets on after a minute or two it crashes i have tried wiping his player data and that did nothing and every time it crashes he is in a different area

**Comment by WhitePhant0m** [comment] 2020-08-20 14:32
Seems to be a duplicate of #42

**Comment by WhitePhant0m** [comment] 2020-08-26 23:19
Again, duplicate of #42.

**Closed by WhitePhant0m** 2020-08-26 23:19 UTC
