### ISSUE TITLE
[1.16.5][1.8.3] Crash on Startup

### ISSUE THREAD

**Issue by cavy8** [AllTheMods/ATM-6#2436] opened 2021-09-24 03:26 UTC
**Describe the bug**
The game crashes shortly after startup, before reaching the title screen.

**To Reproduce**
1. Start the game

**Additional context**
This is the second time this has happened - it fixes with a fresh reinstall. I don't have any worlds, play entirely on a server.

**Logs**
https://pastebin.com/v6ygd252

**Comment by cavy8** [comment] 2021-09-26 03:35
Just dropping in to note that the issue does persist in 1.8.4 as well :)

**Comment by cavy8** [comment] 2021-09-26 03:39
Ope! Looks like there might be some more information about a fix [here](https://github.com/AOCAWOL/BYG-1/issues/34). I hope this helps!

**Comment by oliverrook** [comment] 2021-09-26 13:04
Just updated to 1.8.4 and the issue is back and the fix did not work this time.

**Comment by wendylady** [comment] 2021-09-30 00:24
I got it fixed by using MulitMC and changing the java version to what it auto-suggested. It seems that for some odd reason if you have more than one java installed, let say you also have been running  1.17 or above, it then tries to use that java and not the one need for ATM6 newest builds. This also happens on some other 1.16 pack. I hope this helps at least someone.

**Comment by Pdiddy973** [comment] 2021-10-02 02:05
1.8.3/4 both work not an issue witht he pack, as mentioned above check java versions/launcher settings feel free to ask in [discord](https://discord.gg/K5FBPYa)

**Closed by Pdiddy973** 2021-10-02 02:05 UTC
Labels: Bug
