### ISSUE TITLE
Allthemodium lacks tinker part recipes

### ISSUE THREAD

**Issue by ArashkInGithub** [AllTheMods/ATM-6#2030] opened 2021-07-19 08:00 UTC
Hello,
Sorry again for opening an issue which is directly unrelated to the pack. But the issue is pretty straightforward. You can't make tinker parts with the allthemodium materials. I am NOT using the ATM 6 pack.

Allthemodium version: 1.5.6-1.16.5-36.1.23

**Comment by thevortex** [comment] 2021-07-20 03:25
update allthemodium to newest 1.5.8

**Comment by Pdiddy973** [comment] 2021-07-20 04:09
Duplicate of #2027

**Closed by Pdiddy973** 2021-07-20 04:09 UTC
