### ISSUE TITLE
[Crash]: Game crashes on blueprint initiation with the MineColonies-mod

### ISSUE THREAD

**Issue by Quitschie** [AllTheMods/ATM-6#2860] opened 2022-01-05 09:33 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.16

### What happened?

I started placing (RightClick) an item (TownHall) from the modpack MineColonies on the ground.

The game asked me if I would like to place it directly or with the BuildTool (an item from MineColonies).
I chose the option "Place with BuildTool" (cannot remember the correct spelling). After that the game crashed.

I tried the other option -> place it directly. It worked fine, but after the TownHall, I had to place a SupplyCamp or SupplyShip.
After crafting them, I tried to place both, but the game crashed for both items.

In my opinion the mod wants to start a blueprint-mode, but it fails for some reason and the game crashes.

The Crash Log is from placing the item SupplyCamp.

### Crash Log

https://gist.github.com/Quitschie/459e8ff539033ad337a71b60ee45f87c

**Comment by Tommy1856** [comment] 2022-01-05 12:09
I hate to be that guy but thought I'd let whoever finds a fix know that I'm having the same issue so it's not just a rare occurrence or one off error. 

I'm running a local server on the same PC and my client just crashes while using the build tool.

**Comment by SleepyFanjo** [comment] 2022-01-05 17:39
My game crashes too when trying to place a Supply Camp

**Comment by TheMrCaveman** [comment] 2022-01-05 19:24
same issue here most likely structure and minecolonies are not matching

**Comment by Thaendril** [comment] 2022-01-06 18:09
Exact same issue happens with the supply boat and camp, have crafted both to try it out and in various places.  The second you click it crashes into the above blueprint error.

**Comment by radiomike** [comment] 2022-01-06 18:41
Duplicate of #2847

Update the observable mod

**Comment by Thaendril** [comment] 2022-01-06 19:49
Can confirm updating Observable to Observable-0.2.1-forge.jar fixes this issue

**Comment by jeremiahwinsley** [comment] 2022-01-07 02:14
Fixed in 1.8.17.

**Closed by jeremiahwinsley** 2022-01-07 02:14 UTC
Labels: Crash
