### ISSUE TITLE
[Crash]: placing minecolonies supply camp or ship will crash client

### ISSUE THREAD

**Issue by TheMrCaveman** [AllTheMods/ATM-6#2862] opened 2022-01-05 19:23 UTC
### Possible Fixes

No

### Modpack Version

1.8.16

### What happened?

try to place a supply camp or ship from minecolonies and client crashes.

https://pastebin.com/YJQ3be0b

### Crash Log

https://pastebin.com/YJQ3be0b

**Comment by TheMrCaveman** [comment] 2022-01-05 22:02
caused by doubleslab mod
https://github.com/tasgon/observable/issues/23

**Comment by radiomike** [comment] 2022-01-05 22:06
Duplicate of #2847

**Comment by jeremiahwinsley** [comment] 2022-01-07 02:14
Fixed in 1.8.17.

**Closed by jeremiahwinsley** 2022-01-07 02:14 UTC
Labels: Crash
