### ISSUE TITLE
[Bug]: Cobblestone no longer valid ingredient for stone tools other than the pickaxe

### ISSUE THREAD

**Issue by F4LK5** [AllTheMods/ATM-6#2467] opened 2021-09-30 07:53 UTC
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

I attempted to craft a stone shovel. When inserting the recipe from JEI it pulls items with tag forge:stone but not cobblestone. Also unable to craft other stone tools except the pickaxe. Im guessing someone changed a recipe tag and unintentionally altered core gameplay recipes?

### latest.log

https://gist.github.com/F4LK5/4217f28cebdfd2e969eec1323bfe2f93

**Comment by ladylexxie** [comment] 2021-09-30 12:47
Duplicate of #2464

**Closed by ladylexxie** 2021-09-30 12:47 UTC
Labels: Bug
