### ISSUE TITLE
Wrong mob seeds in current version of mystical agriculture

### ISSUE THREAD

**Issue by BrettMoan** [AllTheMods/ATM-6#2449] opened 2021-09-25 20:23 UTC
**Describe the bug**
In the latest (1.8.3) version of the pack, the version of mystical agriculture has an issue where mob seeds can not be obtained. 

Mystical agg needs updated as the mod author has fixed it. 

**To Reproduce**
1. Try to produce different mob seeds with the mystical agriculture altars. Right now each essence level will only produce one type of seed, no matter what mob jars (even empty mob jars) are placed on the alter. 

**Additional context**

See https://github.com/The-Nexus-Project/Limitless-3/issues/240 where this bug as also reported in another mod pack with the same version of mystical agg.

**Comment by radiomike** [comment] 2021-09-25 20:26
Duplicate of #2365

**Closed** 2021-09-25 20:49 UTC
Labels: Bug
